# Project Title
### Data Engineering Capstone Project

#### Project Summary
--describe your project at a high level--

The project follows the follow steps:
* Step 1: Scope the Project and Gather Data
* Step 2: Explore and Assess the Data
* Step 3: Define the Data Model
* Step 4: Run ETL to Model the Data
* Step 5: Complete Project Write Up

In [1]:
# Do all imports and installs here
from pyspark.sql import SparkSession
import pandas as pd

In [2]:
from extractor import Extractor
from transformer import Transformer

### Step 1: Scope the Project and Gather Data

#### Scope 
Explain what you plan to do in the project in more detail. What data do you use? What is your end solution look like? What tools did you use? etc>

#### Describe and Gather Data 
Describe the data sets you're using. Where did it come from? What type of information is included?

In [3]:
filepaths = {
    'i94' : './data/18-83510-I94-Data-2016/i94_apr16_sub.sas7bdat',
    'airports' : './data/airport-codes_csv.csv',
    'states' : './data/states.csv',
    'transport_modes' : './data/transport_mode.csv',
    'visa' : './data/visa.csv',
    'cities' : './data/us-cities-demographics.csv'
}

In [4]:
spark = SparkSession \
        .builder \
        .config("spark.jars.packages","saurfang:spark-sas7bdat:2.0.0-s_2.11")\
        .enableHiveSupport()\
        .getOrCreate()

In [5]:
extractor = Extractor(spark, filepaths)

In [6]:
df_airports = extractor.get_airport_data()
df_cities = extractor.get_cities_data()
df_states = extractor.get_states_data()
df_trasnp_modes = extractor.get_transp_mode_data()
df_visas = extractor.get_visa_data()

In [7]:
df_airports.toPandas()

,ident,type,name,elevation_ft,continent,iso_country,iso_region,municipality,gps_code,iata_code,local_code,coordinates
0,00A,heliport,Total Rf Heliport,11,NA,US,US-PA,Bensalem,00A,None,00A,"-74.93360137939453, 40.07080078125"
1,00AA,small_airport,Aero B Ranch Airport,3435,NA,US,US-KS,Leoti,00AA,None,00AA,"-101.473911, 38.704022"
2,00AK,small_airport,Lowell Field,450,NA,US,US-AK,Anchor Point,00AK,None,00AK,"-151.695999146, 59.94919968"
3,00AL,small_airport,Epps Airpark,820,NA,US,US-AL,Harvest,00AL,None,00AL,"-86.77030181884766, 34.86479949951172"
4,00AR,closed,Newport Hospital & Clinic Heliport,237,NA,US,US-AR,Newport,None,None,None,"-91.254898, 35.6087"
5,00AS,small_airport,Fulton Airport,1100,NA,US,US-OK,Alex,00AS,None,00AS,"-97.8180194, 34.9428028"
6,00AZ,small_airport,Cordes Airport,3810,NA,US,US-AZ,Cordes,00AZ,None,00AZ,"-112.16500091552734, 34.305599212646484"
7,00CA,small_airport,Goldstone /Gts/ Airport,3038,NA,US,US-CA,Barstow,00CA,None,00CA,"-116.888000488, 35.350498199499995"
8,00CL,small_airport,Williams Ag Airport,87,NA,US,US-CA,Biggs,00CL,None,00CL,"-121.763427, 39.427188"
9,00CN,heliport,Kitchen Creek Helibase Heliport,3350,NA,US,US-CA,Pine Valley,00CN,None,00CN,"-116.4597417, 32.7273736"
10,00CO,closed,Cass Field,4830,NA,US,US-CO,Briggsdale,None,None,None,"-104.344002, 40.622202"
11,00FA,small_airport,Grass Patch Airport,53,NA,US,US-FL,Bushnell,00FA,None,00FA,"-82.21900177001953, 28.64550018310547"
12,00FD,heliport,Ringhaver Heliport,25,NA,US,US-FL,Riverview,00FD,None,00FD,"-82.34539794921875, 28.846599578857422"
13,00FL,small_airport,River Oak Airport,35,NA,US,US-FL,Okeechobee,00FL,None,00FL,"-80.96920013427734, 27.230899810791016"
14,00GA,small_airport,Lt World Airport,700,NA,US,US-GA,Lithonia,00GA,None,00GA,"-84.06829833984375, 33.76750183105469"
15,00GE,heliport,Caffrey Heliport,957,NA,US,US-GA,Hiram,00GE,None,00GE,"-84.73390197753906, 33.88420104980469"
16,00HI,heliport,Kaupulehu Heliport,43,NA,US,US-HI,Kailua/Kona,00HI,None,00HI,"-155.980233, 19.832715"
17,00ID,small_airport,Delta Shores Airport,2064,NA,US,US-ID,Clark Fork,00ID,None,00ID,"-116.21399688720703, 48.145301818847656"
18,00IG,small_airport,Goltl Airport,3359,NA,US,US-KS,McDonald,00IG,None,00IG,"-101.395994, 39.724028"
19,00II,heliport,Bailey Generation Station Heliport,600,NA,US,US-IN,Chesterton,00II,None,00II,"-87.122802734375, 41.644500732421875"
20,00IL,small_airport,Hammer Airport,840,NA,US,US-IL,Polo,00IL,None,00IL,"-89.5604019165039, 41.97840118408203"
21,00IN,heliport,St Mary Medical Center Heliport,634,NA,US,US-IN,Hobart,00IN,None,00IN,"-87.2605972290039, 41.51139831542969"
22,00IS,small_airport,Hayenga's Cant Find Farms Airport,820,NA,US,US-IL,Kings,00IS,None,00IS,"-89.1229019165039, 40.02560043334961"
23,00KS,small_airport,Hayden Farm Airport,1100,NA,US,US-KS,Gardner,00KS,None,00KS,"-94.93049621582031, 38.72779846191406"
24,00KY,small_airport,Robbins Roost Airport,1265,NA,US,US-KY,Stanford,00KY,None,00KY,"-84.61969757080078, 37.409400939941406"
25,00LA,heliport,Shell Chemical East Site Heliport,15,NA,US,US-LA,Gonzales,00LA,None,00LA,"-90.980833, 30.191944"
26,00LL,heliport,Ac & R Components Heliport,600,NA,US,US-IL,Chatham,00LL,None,00LL,"-89.70559692382812, 39.66529846191406"
27,00LS,small_airport,Lejeune Airport,12,NA,US,US-LA,Esterwood,00LS,None,00LS,"-92.42939758300781, 30.13629913330078"
28,00MD,small_airport,Slater Field,45,NA,US,US-MD,Federalsburg,00MD,None,00MD,"-75.75379943847656, 38.75709915161133"
29,00MI,heliport,Dow Chemical Heliport,588,NA,US,US-MI,Ludington,00MI,None,00MI,"-86.41670227050781, 43.94940185546875"
...,...,...,...,...,...,...,...,...,...,...,...,...
55045,ZYAS,medium_airport,Anshan Air Base,None,AS,CN,CN-21,Anshan,ZYAS,AOG,None,"122.853996, 41.105301"
55046,ZYCC,medium_airport,Longjia Airport,706,AS,CN,CN-22,Changchun,ZYCC,CGQ,None,"125.684997559, 43.9962005615"
55047,ZYCH,medium_airport,Changhai Airport,80,AS,CN,CN-21,Changhai,ZYCH,CNI,None,"122.666944444, 39.2666666667"
55048,ZYCY,medium_airport,Chaoyang Airport,568,AS,CN,CN-21,Chaoyang,ZYCY,CHG,None,"120.434998, 41.538101"
55049,ZYDU,medium_airport,Wudalianchi Dedu Airport,984,AS,CN,CN-23,Wudalianchi,ZYDU,DTU,None,"126.133, 48.445"
55050,ZYFX,small_airport,Fuxin Airport,548,AS,CN,CN-21,Fuxin,ZYFX,None,None,"121.718122, 42.069014"
55051,ZYFY,medium_airport,Dongji Aiport,None,AS,CN,CN-23,Fuyuan,ZYFY,FYJ,None,"134.366447, 48.199494"
55052,ZYHB,large_airport,Taiping Airport,457,AS,CN,CN-23,Harbin,ZYHB,HRB,None,"126.25, 45.6234016418457"
55053,ZYHE,medium_airport,Heihe Airport,8530,AS,CN,CN-23,Heihe,ZYHE,HEK,None,"127.308883667, 50.1716209371"
55054,ZYJL,small_airport,Jilin Airport,None,AS,CN,CN-22,Jilin,ZYJL,JIL,None,"126.396004, 44.002201"
55055,ZYJM,medium_airport,Jiamusi Airport,262,AS,CN,CN-23,Jiamusi,ZYJM,JMU,None,"130.464996338, 46.84339904789999"
55056,ZYJS,medium_airport,Jiansanjiang Airport,None,AS,CN,CN-23,Jiansanjiang,ZYJS,JSJ,None,"132.660278, 47.11"
55057,ZYJX,medium_airport,Jixi Xingkaihu Airport,760,AS,CN,CN-23,Jixi,ZYJX,JXA,None,"131.193, 45.293"
55058,ZYJZ,medium_airport,Jinzhou Airport,None,AS,CN,CN-21,Jinzhou,ZYJZ,JNZ,None,"121.06199645996094, 41.10139846801758"
55059,ZYLD,medium_airport,Lindu Airport,791,AS,CN,CN-23,Yichun,ZYLD,LDS,None,"129.019125, 47.7520555556"
55060,ZYLS,medium_airport,Yushu Batang Airport,12816,AS,CN,CN-63,Yushu,ZYLS,YUS,None,"97.0363888889, 32.836388888900004"
55061,ZYMD,medium_airport,Mudanjiang Hailang International Airport,883,AS,CN,CN-23,Mudanjiang,ZYMD,MDG,None,"129.569000244, 44.5241012573"
55062,ZYMH,medium_airport,Gu-Lian Airport,1836,AS,CN,CN-23,Mohe,ZYMH,OHE,None,"122.43, 52.912777777799995"
55063,ZYQQ,medium_airport,Qiqihar Sanjiazi Airport,477,AS,CN,CN-23,Qiqihar,ZYQQ,NDG,None,"123.91799926757812, 47.239601135253906"
55064,ZYSQ,medium_airport,Songyuan Chaganhu Airport,459,AS,CN,CN-22,Qian Gorlos Mongol Autonomous County,ZYSQ,YSQ,None,"124.550178, 44.938114"
55065,ZYTH,small_airport,Tahe Airport,1240,AS,CN,CN-23,Tahe,ZYTH,None,None,"124.720222222, 52.2244444444"
55066,ZYTL,large_airport,Zhoushuizi Airport,107,AS,CN,CN-21,Dalian,ZYTL,DLC,None,"121.53900146484375, 38.9656982421875"
55067,ZYTN,medium_airport,Tonghua Sanyuanpu Airport,1200,AS,CN,CN-22,Tonghua,ZYTN,TNH,None,"125.703333333, 42.2538888889"
55068,ZYTX,large_airport,Taoxian Airport,198,AS,CN,CN-21,Shenyang,ZYTX,SHE,None,"123.48300170898438, 41.639801025390625"
55069,ZYYJ,medium_airport,Yanji Chaoyangchuan Airport,624,AS,CN,CN-22,Yanji,ZYYJ,YNJ,None,"129.451004028, 42.8828010559"
55070,ZYYK,medium_airport,Yingkou Lanqi Airport,0,AS,CN,CN-21,Yingkou,ZYYK,YKH,None,"122.3586, 40.542524"
55071,ZYYY,medium_airport,Shenyang Dongta Airport,None,AS,CN,CN-21,Shenyang,ZYYY,None,None,"123.49600219726562, 41.784400939941406"
55072,ZZ-0001,heliport,Sealand Helipad,40,EU,GB,GB-ENG,Sealand,None,None,None,"1.4825, 51.894444"
55073,ZZ-0002,small_airport,Glorioso Islands Airstrip,11,AF,TF,TF-U-A,Grande Glorieuse,None,None,None,"47.296388888900005, -11.584277777799999"
55074,ZZZZ,small_airport,Satsuma IÅjima Airport,338,AS,JP,JP-46,Mishima-Mura,RJX7,None,None,"130.270556, 30.784722"

In [8]:
df_cities.toPandas()

,City,State,Median Age,Male Population,Female Population,Total Population,Number of Veterans,Foreign-born,Average Household Size,State Code,Race,Count
0,Silver Spring,Maryland,33.8,40601,41862,82463,1562,30908,2.6,MD,Hispanic or Latino,25924
1,Quincy,Massachusetts,41.0,44129,49500,93629,4147,32935,2.39,MA,White,58723
2,Hoover,Alabama,38.5,38040,46799,84839,4819,8229,2.58,AL,Asian,4759
3,Rancho Cucamonga,California,34.5,88127,87105,175232,5821,33878,3.18,CA,Black or African-American,24437
4,Newark,New Jersey,34.6,138040,143873,281913,5829,86253,2.73,NJ,White,76402
5,Peoria,Illinois,33.1,56229,62432,118661,6634,7517,2.4,IL,American Indian and Alaska Native,1343
6,Avondale,Arizona,29.1,38712,41971,80683,4815,8355,3.18,AZ,Black or African-American,11592
7,West Covina,California,39.8,51629,56860,108489,3800,37038,3.56,CA,Asian,32716
8,O'Fallon,Missouri,36.0,41762,43270,85032,5783,3269,2.77,MO,Hispanic or Latino,2583
9,High Point,North Carolina,35.5,51751,58077,109828,5204,16315,2.65,NC,Asian,11060
10,Folsom,California,40.9,41051,35317,76368,4187,13234,2.62,CA,Hispanic or Latino,5822
11,Folsom,California,40.9,41051,35317,76368,4187,13234,2.62,CA,American Indian and Alaska Native,998
12,Philadelphia,Pennsylvania,34.1,741270,826172,1567442,61995,205339,2.61,PA,Asian,122721
13,Wichita,Kansas,34.6,192354,197601,389955,23978,40270,2.56,KS,Hispanic or Latino,65162
14,Wichita,Kansas,34.6,192354,197601,389955,23978,40270,2.56,KS,American Indian and Alaska Native,8791
15,Fort Myers,Florida,37.3,36850,37165,74015,4312,15365,2.45,FL,White,50169
16,Pittsburgh,Pennsylvania,32.9,149690,154695,304385,17728,28187,2.13,PA,White,208863
17,Laredo,Texas,28.8,124305,131484,255789,4921,68427,3.66,TX,American Indian and Alaska Native,1253
18,Berkeley,California,32.5,60142,60829,120971,3736,25000,2.35,CA,Asian,27089
19,Santa Clara,California,35.2,63278,62938,126216,4426,52281,2.75,CA,White,55847
20,Allen,Pennsylvania,33.5,60626,59581,120207,5691,19652,2.67,PA,Black or African-American,22304
21,Hampton,Virginia,35.5,66214,70240,136454,19638,6204,2.48,VA,Black or African-American,70303
22,Bolingbrook,Illinois,33.7,36295,35801,72096,2951,15212,3.42,IL,American Indian and Alaska Native,323
23,Frederick,Maryland,36.1,33146,36336,69482,3870,14211,2.48,MD,White,49181
24,Sparks,Nevada,36.1,47780,48318,96098,7315,15690,2.63,NV,Hispanic or Latino,29159
25,Rancho Cordova,California,33.8,34844,36182,71026,4590,17020,2.86,CA,Asian,12653
26,Westminster,Colorado,37.8,54866,58251,113117,6512,11361,2.63,CO,Hispanic or Latino,23355
27,Lakewood,Colorado,37.7,76013,76576,152589,9988,14169,2.29,CO,Hispanic or Latino,33630
28,Flint,Michigan,35.3,48984,49313,98297,3757,2138,2.38,MI,White,44786
29,New Haven,Connecticut,29.9,63765,66545,130310,2567,25871,2.48,CT,American Indian and Alaska Native,2205
...,...,...,...,...,...,...,...,...,...,...,...,...
2861,Scranton,Pennsylvania,38.5,37975,39137,77112,5059,8069,2.39,PA,Asian,4722
2862,Aurora,Colorado,34.2,177899,180971,358870,25158,65816,2.82,CO,Asian,24673
2863,Redlands,California,36.2,33993,37035,71028,3445,8681,2.82,CA,Hispanic or Latino,19698
2864,Alhambra,California,41.0,42184,43388,85572,1673,44441,2.89,CA,Hispanic or Latino,31386
2865,Alhambra,California,41.0,42184,43388,85572,1673,44441,2.89,CA,Black or African-American,1905
2866,Rio Rancho,New Mexico,38.3,47251,46904,94155,8527,5200,2.86,NM,Black or African-American,3970
2867,Wyoming,Michigan,32.8,35967,39310,75277,3447,8612,2.65,MI,American Indian and Alaska Native,2444
2868,Reading,Pennsylvania,29.4,43668,44205,87873,2580,17043,2.95,PA,Asian,903
2869,Rialto,California,31.6,49902,53235,103137,2036,32741,3.83,CA,American Indian and Alaska Native,1065
2870,Tallahassee,Florida,26.2,89390,100504,189894,9575,16720,2.38,FL,Asian,10035
2871,Hemet,California,36.8,38622,45251,83873,5613,13330,2.97,CA,Asian,3697
2872,Aurora,Illinois,31.7,101964,101751,203715,4988,50980,3.3,IL,Black or African-American,23736
2873,Carmel,Indiana,39.9,42928,46101,89029,2723,9645,2.71,IN,White,77178
2874,Glendale,California,42.1,98181,102844,201025,4448,111510,2.69,CA,Hispanic or Latino,30807
2875,Des Moines,Iowa,34.5,103726,106591,210317,11780,23857,2.41,IA,White,168057
2876,College Station,Texas,22.9,54125,53774,107899,2471,16145,2.52,TX,White,84892
2877,Peoria,Arizona,36.9,80139,91103,171242,13019,14260,2.97,AZ,Asian,6631
2878,Charlotte,North Carolina,34.3,396646,430475,827121,36046,128897,2.52,NC,American Indian and Alaska Native,8746
2879,Lafayette,Indiana,33.5,34313,36857,71170,5045,5697,2.19,IN,Hispanic or Latino,9151
2880,Abilene,Texas,31.3,65212,60664,125876,9367,8129,2.64,TX,Black or African-American,14449
2881,Gulfport,Mississippi,35.1,33108,38764,71872,6646,3072,2.54,MS,White,42870
2882,Davis,California,26.3,33493,34163,67656,2176,13997,2.69,CA,American Indian and Alaska Native,779
2883,Los Angeles,California,35.0,1958998,2012898,3971896,85417,1485425,2.86,CA,Black or African-American,404868
2884,Mount Vernon,New York,38.5,31876,36745,68621,2064,23777,2.85,NY,Hispanic or Latino,9446
2885,Lynchburg,Virginia,28.7,38614,41198,79812,4322,4364,2.48,VA,White,53727
2886,Stockton,California,32.5,150976,154674,305650,12822,79583,3.16,CA,American Indian and Alaska Native,19834
2887,Southfield,Michigan,41.6,31369,41808,73177,4035,4011,2.27,MI,American Indian and Alaska Native,983
2888,Indianapolis,Indiana,34.1,410615,437808,848423,42186,72456,2.53,IN,White,553665
2889,Somerville,Massachusetts,31.0,41028,39306,80334,2103,22292,2.43,MA,American Indian and Alaska Native,374
2890,Coral Springs,Florida,37.2,63316,66186,129502,4724,38552,3.17,FL,White,90896

In [9]:
df_states.toPandas()

   state_code              state
0          AL            ALABAMA
1          AK             ALASKA
2          AZ            ARIZONA
3          AR           ARKANSAS
4          CA         CALIFORNIA
5          CO           COLORADO
6          CT        CONNECTICUT
7          DE           DELAWARE
8          DC  DIST. OF COLUMBIA
9          FL            FLORIDA
10         GA            GEORGIA
11         GU               GUAM
12         HI             HAWAII
13         ID              IDAHO
14         IL           ILLINOIS
15         IN            INDIANA
16         IA               IOWA
17         KS             KANSAS
18         KY           KENTUCKY
19         LA          LOUISIANA
20         ME              MAINE
21         MD           MARYLAND
22         MA      MASSACHUSETTS
23         MI           MICHIGAN
24         MN          MINNESOTA
25         MS        MISSISSIPPI
26         MO           MISSOURI
27         MT            MONTANA
28         NC        N. CAROLINA
29         ND          N. DAKOTA
30         NE           NEBRASKA
31         NV             NEVADA
32         NH      NEW HAMPSHIRE
33         NJ         NEW JERSEY
34         NM         NEW MEXICO
35         NY           NEW YORK
36         OH               OHIO
37         OK           OKLAHOMA
38         OR             OREGON
39         PA       PENNSYLVANIA
40         PR        PUERTO RICO
41         RI       RHODE ISLAND
42         SC        S. CAROLINA
43         SD          S. DAKOTA
44         TN          TENNESSEE
45         TX              TEXAS
46         UT               UTAH
47         VT            VERMONT
48         VI     VIRGIN ISLANDS
49         VA           VIRGINIA
50         WV        W. VIRGINIA
51         WA         WASHINGTON
52         WI          WISCONSON
53         WY           WYOMING
54         99    All Other Codes

In [10]:
df_trasnp_modes.toPandas()

  transport_mode_code transport_mode
0                   1            Air
1                   2            Sea
2                   3           Land
3                   9   Not reported

In [11]:
df_visas.toPandas()

  visa_code visa_type
0         1  Business
1         2  Pleasure
2         3   Student

In [12]:
df_i94 = extractor.get_i94_data()
df_i94.printSchema()

root
 |-- cicid: double (nullable = true)
 |-- i94yr: double (nullable = true)
 |-- i94mon: double (nullable = true)
 |-- i94cit: double (nullable = true)
 |-- i94res: double (nullable = true)
 |-- i94port: string (nullable = true)
 |-- arrdate: double (nullable = true)
 |-- i94mode: double (nullable = true)
 |-- i94addr: string (nullable = true)
 |-- depdate: double (nullable = true)
 |-- i94bir: double (nullable = true)
 |-- i94visa: double (nullable = true)
 |-- count: double (nullable = true)
 |-- dtadfile: string (nullable = true)
 |-- visapost: string (nullable = true)
 |-- occup: string (nullable = true)
 |-- entdepa: string (nullable = true)
 |-- entdepd: string (nullable = true)
 |-- entdepu: string (nullable = true)
 |-- matflag: string (nullable = true)
 |-- biryear: double (nullable = true)
 |-- dtaddto: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- insnum: string (nullable = true)
 |-- airline: string (nullable = true)
 |-- admnum: double (nullable = true)
 |-- fltno: string (nullable = true)
 |-- visatype: string (nullable = true)

In [13]:
df_cities.toPandas()['State Code'].unique()

array(['MD', 'MA', 'AL', 'CA', 'NJ', 'IL', 'AZ', 'MO', 'NC', 'PA', 'KS',
       'FL', 'TX', 'VA', 'NV', 'CO', 'MI', 'CT', 'MN', 'UT', 'AR', 'TN',
       'OK', 'WA', 'NY', 'GA', 'NE', 'KY', 'SC', 'LA', 'NM', 'IA', 'RI',
       'PR', 'DC', 'WI', 'OR', 'NH', 'ND', 'DE', 'OH', 'ID', 'IN', 'AK',
       'MS', 'HI', 'SD', 'ME', 'MT'], dtype=object)

In [14]:
#write to parquet
#df_spark.write.parquet("sas_data")
#df_spark=spark.read.parquet("sas_data")

### Step 2: Explore and Assess the Data
#### Explore the Data 
Identify data quality issues, like missing values, duplicate data, etc.

#### Cleaning Steps
Document steps necessary to clean the data

In [15]:
#states_list = [x.state_code for x in df_states.select('state_code').distinct().collect()]

In [16]:
df_airport_clean = Transformer.clean_airports(df_airports, df_states)
df_airport_clean.toPandas()

,ident,airport_type,name,elevation_ft,continent,iso_country,municipality,gps_code,iata_code,local_code,coordinates,state
0,00A,heliport,Total Rf Heliport,11.0,NA,US,Bensalem,00A,None,00A,"-74.93360137939453, 40.07080078125",PA
1,00AA,small_airport,Aero B Ranch Airport,3435.0,NA,US,Leoti,00AA,None,00AA,"-101.473911, 38.704022",KS
2,00AK,small_airport,Lowell Field,450.0,NA,US,Anchor Point,00AK,None,00AK,"-151.695999146, 59.94919968",AK
3,00AL,small_airport,Epps Airpark,820.0,NA,US,Harvest,00AL,None,00AL,"-86.77030181884766, 34.86479949951172",AL
4,00AS,small_airport,Fulton Airport,1100.0,NA,US,Alex,00AS,None,00AS,"-97.8180194, 34.9428028",OK
5,00AZ,small_airport,Cordes Airport,3810.0,NA,US,Cordes,00AZ,None,00AZ,"-112.16500091552734, 34.305599212646484",AZ
6,00CA,small_airport,Goldstone /Gts/ Airport,3038.0,NA,US,Barstow,00CA,None,00CA,"-116.888000488, 35.350498199499995",CA
7,00CL,small_airport,Williams Ag Airport,87.0,NA,US,Biggs,00CL,None,00CL,"-121.763427, 39.427188",CA
8,00CN,heliport,Kitchen Creek Helibase Heliport,3350.0,NA,US,Pine Valley,00CN,None,00CN,"-116.4597417, 32.7273736",CA
9,00FA,small_airport,Grass Patch Airport,53.0,NA,US,Bushnell,00FA,None,00FA,"-82.21900177001953, 28.64550018310547",FL
10,00FD,heliport,Ringhaver Heliport,25.0,NA,US,Riverview,00FD,None,00FD,"-82.34539794921875, 28.846599578857422",FL
11,00FL,small_airport,River Oak Airport,35.0,NA,US,Okeechobee,00FL,None,00FL,"-80.96920013427734, 27.230899810791016",FL
12,00GA,small_airport,Lt World Airport,700.0,NA,US,Lithonia,00GA,None,00GA,"-84.06829833984375, 33.76750183105469",GA
13,00GE,heliport,Caffrey Heliport,957.0,NA,US,Hiram,00GE,None,00GE,"-84.73390197753906, 33.88420104980469",GA
14,00HI,heliport,Kaupulehu Heliport,43.0,NA,US,Kailua/Kona,00HI,None,00HI,"-155.980233, 19.832715",HI
15,00ID,small_airport,Delta Shores Airport,2064.0,NA,US,Clark Fork,00ID,None,00ID,"-116.21399688720703, 48.145301818847656",ID
16,00IG,small_airport,Goltl Airport,3359.0,NA,US,McDonald,00IG,None,00IG,"-101.395994, 39.724028",KS
17,00II,heliport,Bailey Generation Station Heliport,600.0,NA,US,Chesterton,00II,None,00II,"-87.122802734375, 41.644500732421875",IN
18,00IL,small_airport,Hammer Airport,840.0,NA,US,Polo,00IL,None,00IL,"-89.5604019165039, 41.97840118408203",IL
19,00IN,heliport,St Mary Medical Center Heliport,634.0,NA,US,Hobart,00IN,None,00IN,"-87.2605972290039, 41.51139831542969",IN
20,00IS,small_airport,Hayenga's Cant Find Farms Airport,820.0,NA,US,Kings,00IS,None,00IS,"-89.1229019165039, 40.02560043334961",IL
21,00KS,small_airport,Hayden Farm Airport,1100.0,NA,US,Gardner,00KS,None,00KS,"-94.93049621582031, 38.72779846191406",KS
22,00KY,small_airport,Robbins Roost Airport,1265.0,NA,US,Stanford,00KY,None,00KY,"-84.61969757080078, 37.409400939941406",KY
23,00LA,heliport,Shell Chemical East Site Heliport,15.0,NA,US,Gonzales,00LA,None,00LA,"-90.980833, 30.191944",LA
24,00LL,heliport,Ac & R Components Heliport,600.0,NA,US,Chatham,00LL,None,00LL,"-89.70559692382812, 39.66529846191406",IL
25,00LS,small_airport,Lejeune Airport,12.0,NA,US,Esterwood,00LS,None,00LS,"-92.42939758300781, 30.13629913330078",LA
26,00MD,small_airport,Slater Field,45.0,NA,US,Federalsburg,00MD,None,00MD,"-75.75379943847656, 38.75709915161133",MD
27,00MI,heliport,Dow Chemical Heliport,588.0,NA,US,Ludington,00MI,None,00MI,"-86.41670227050781, 43.94940185546875",MI
28,00MN,small_airport,Battle Lake Municipal Airport,1365.0,NA,US,Battle Lake,00MN,None,00MN,"-95.70030212402344, 46.29999923706055",MN
29,00MO,small_airport,Cooper Flying Service Airport,970.0,NA,US,Alba,00MO,None,00MO,"-94.412399291992, 37.202800750732",MO
...,...,...,...,...,...,...,...,...,...,...,...,...
21401,Y91,small_airport,Home Acres Sky Ranch Airport,1247.0,NA,US,Lake City,Y91,None,Y91,"-85.17120361328125, 44.3203010559082",MI
21402,Y96,small_airport,Leo E. Goetz County Airport,830.0,NA,US,Onaway,Y96,None,Y96,"-84.2249984741211, 45.37080001831055",MI
21403,Y98,small_airport,Grand Marais Airport,838.0,NA,US,Grand Marais,Y98,None,Y98,"-85.91680145263672, 46.62080001831055",MI
21404,Y99,small_airport,Trulson Field,2105.0,NA,US,Plaza,Y99,None,Y99,"-101.9530029296875, 48.030601501464844",ND
21405,Z13,small_airport,Akiachak Airport,23.0,NA,US,Akiachak,Z13,KKI,Z13,"-161.42199707031, 60.904800415039",AK
21406,Z14,small_airport,Tazlina Airport,2450.0,NA,US,Tazlina,Z14,None,Z14,"-146.46099853515625, 62.06480026245117",AK
21407,Z17,small_airport,Ophir Airport,575.0,NA,US,Ophir,Z17,None,Z17,"-156.52999877929688, 63.145999908447266",AK
21408,Z20,seaplane_base,Tuntutuliak Seaplane Base,15.0,NA,US,Tuntutuliak,Z20,None,Z20,"-162.666000366, 60.3414993286",AK
21409,Z25,small_airport,Tripod Airport,225.0,NA,US,Aleknagik,Z25,None,Z25,"-158.557755, 59.263146",AK
21410,Z33,seaplane_base,Aleknagik Seaplane Base,7.0,NA,US,Aleknagik,Z33,None,Z33,"-158.62399291992188, 59.27399826049805",AK
21411,Z40,small_airport,Goose Bay Airport,78.0,NA,US,Goose Bay,Z40,None,Z40,"-149.8459930419922, 61.394500732421875",AK
21412,Z41,small_airport,Lake Hood Strip,73.0,NA,US,Anchorage,Z41,None,Z41,"-149.96499633789062, 61.1869010925293",AK
21413,Z43,seaplane_base,Tamgas Harbor Seaplane Base,NaN,NA,US,Annette,Z43,None,Z43,"-131.5570068359375, 55.06800079345703",AK
21414,Z47,small_airport,Engstrom Field,143.0,NA,US,Basin Creek,None,None,Z47,"-165.299205, 64.67909",AK
21415,Z48,small_airport,Bear Creek 3 Airport,740.0,NA,US,Bear Creek,Z48,BCC,Z48,"-156.149454117, 63.5733160384",AK
21416,Z52,small_airport,Johnsons Landing Airport,130.0,NA,US,Bear Lake,Z52,None,Z52,"-160.26600646972656, 56.03670120239258",AK
21417,Z55,small_airport,Lake Louise Airport,2450.0,NA,US,Lake Louise,Z55,None,Z55,"-146.57899475097656, 62.293701171875",AK
21418,Z58,seaplane_base,Hangar Lake Seaplane Base,17.0,NA,US,Bethel,None,None,Z58,"-161.727024, 60.803324",AK
21419,Z59,seaplane_base,Bethel Seaplane Base,15.0,NA,US,Bethel,Z59,JBT,Z59,"-161.742996216, 60.782001495399996",AK
21420,Z71,seaplane_base,Cape Pole Seaplane Base,0.0,NA,US,Cape Pole,Z71,CZP,Z71,"-133.79699707, 55.9663009644",AK
21421,Z78,seaplane_base,Chignik Bay Seaplane Base,NaN,NA,US,Chignik,Z78,KBW,Z78,"-158.401000977, 56.295600891099994",AK
21422,Z81,small_airport,Salmon Lake Airport,490.0,NA,US,Salmon Lake,Z81,None,Z81,"-165.01300048828125, 64.9092025756836",AK
21423,Z86,small_airport,Clearwater Airport,2900.0,NA,US,Clearwater,Z86,None,Z86,"-147.1790008544922, 63.026798248291016",AK
21424,Z87,seaplane_base,Blinn Lake Seaplane Base,50.0,NA,US,Cold Bay,Z87,None,Z87,"-162.7530059814453, 55.2515983581543",AK
21425,Z90,small_airport,Stampede Airport,1850.0,NA,US,Kantishna,Z90,None,Z90,"-150.3300018310547, 63.74869918823242",AK
21426,Z91,small_airport,Birch Creek Airport,450.0,NA,US,Birch Creek,Z91,KBC,Z91,"-145.824005127, 66.2740020752",AK
21427,Z92,small_airport,Harsens Island Airport,578.0,NA,US,Harsens Island,Z92,None,Z92,"-82.57640075683594, 42.589698791503906",MI
21428,Z93,small_airport,Copper Center 2 Airport,1150.0,NA,US,Copper Center,Z93,CZC,Z93,"-145.294006348, 61.9412002563",AK
21429,Z95,small_airport,Cibecue Airport,5037.0,NA,US,Cibecue,Z95,None,Z95,"-110.44400024414062, 34.003299713134766",AZ
21430,ZNC,small_airport,Nyac Airport,460.0,NA,US,Nyac,ZNC,ZNC,ZNC,"-159.994003296, 60.9807014465",AK

In [17]:
df_airport_clean.printSchema()

root
 |-- ident: string (nullable = true)
 |-- airport_type: string (nullable = true)
 |-- name: string (nullable = true)
 |-- elevation_ft: float (nullable = true)
 |-- continent: string (nullable = true)
 |-- iso_country: string (nullable = true)
 |-- municipality: string (nullable = true)
 |-- gps_code: string (nullable = true)
 |-- iata_code: string (nullable = true)
 |-- local_code: string (nullable = true)
 |-- coordinates: string (nullable = true)
 |-- state: string (nullable = true)

In [18]:
df_airport_clean.select(df_airport_clean.airport_type).distinct().show(666)

+--------------+
|  airport_type|
+--------------+
| large_airport|
|   balloonport|
| seaplane_base|
|      heliport|
|medium_airport|
| small_airport|
+--------------+

In [28]:
df_i94_clean = Transformer.clean_i94_data(df_i94)
df_i94_clean.limit(100).toPandas()

,count,dtadfile,visapost,occup,entdepa,entdepd,entdepu,matflag,gender,airline,...,allowed_to_stay_until,ins_num,admission_num,flight_num,arrival_date_sas,departure_from_usa_sas,visa_type,date_baseline,arrival_date,departure_from_usa
0,1,NaN,None,None,T,None,U,None,None,None,...,10282016,None,1897628485,NaN,20573,NaN,B2,1960-01-01,2016-04-29,None
1,1,20130811.0,SEO,None,G,None,Y,None,M,None,...,D/S,None,2147483647,296.0,20551,NaN,F1,1960-01-01,2016-04-07,None
2,1,20160401.0,None,None,T,O,None,M,M,OS,...,09302016,None,666643185,93.0,20545,20691.0,B2,1960-01-01,2016-04-01,2016-08-25
3,1,20160401.0,None,None,O,O,None,M,None,AA,...,09302016,None,2147483647,199.0,20545,20567.0,B2,1960-01-01,2016-04-01,2016-04-23
4,1,20160401.0,None,None,O,O,None,M,None,AA,...,09302016,None,2147483647,199.0,20545,20567.0,B2,1960-01-01,2016-04-01,2016-04-23
5,1,20160401.0,None,None,O,O,None,M,None,AZ,...,09302016,None,2147483647,602.0,20545,20555.0,B1,1960-01-01,2016-04-01,2016-04-11
6,1,20160401.0,None,None,O,K,None,M,None,AZ,...,09302016,None,2147483647,602.0,20545,20558.0,B2,1960-01-01,2016-04-01,2016-04-14
7,1,20160401.0,None,None,O,K,None,M,None,AZ,...,09302016,None,2147483647,602.0,20545,20558.0,B2,1960-01-01,2016-04-01,2016-04-14
8,1,20160401.0,None,None,O,O,None,M,None,AZ,...,09302016,None,2147483647,602.0,20545,20553.0,B2,1960-01-01,2016-04-01,2016-04-09
9,1,20160401.0,None,None,O,O,None,M,None,AZ,...,09302016,None,2147483647,608.0,20545,20562.0,B1,1960-01-01,2016-04-01,2016-04-18
10,1,20160401.0,None,None,O,O,None,M,None,TK,...,09302016,None,2147483647,1.0,20545,20671.0,B2,1960-01-01,2016-04-01,2016-08-05
11,1,20160401.0,None,None,O,O,None,M,None,MQ,...,09302016,None,2147483647,3348.0,20545,20554.0,B2,1960-01-01,2016-04-01,2016-04-10
12,1,20160401.0,TIA,None,G,O,None,M,M,LH,...,04062016,None,2147483647,422.0,20545,20549.0,B1,1960-01-01,2016-04-01,2016-04-05
13,1,20160401.0,TIA,None,G,O,None,M,F,LH,...,04062016,None,2147483647,422.0,20545,20549.0,B1,1960-01-01,2016-04-01,2016-04-05
14,1,20160401.0,TIA,None,G,O,None,M,M,AZ,...,09302016,None,2147483647,614.0,20545,20561.0,B2,1960-01-01,2016-04-01,2016-04-17
15,1,20160401.0,TIA,None,G,O,None,M,M,OS,...,09302016,None,2147483647,89.0,20545,20578.0,B2,1960-01-01,2016-04-01,2016-05-04
16,1,20160401.0,TIA,None,G,O,None,M,M,OS,...,09302016,None,2147483647,89.0,20545,20611.0,B2,1960-01-01,2016-04-01,2016-06-06
17,1,20160401.0,TIA,None,G,O,None,M,F,TK,...,09302016,None,2147483647,33.0,20545,20554.0,B2,1960-01-01,2016-04-01,2016-04-10
18,1,20160401.0,TIA,None,G,None,None,None,M,AZ,...,09302016,None,2147483647,602.0,20545,NaN,B2,1960-01-01,2016-04-01,None
19,1,20160401.0,TIA,None,T,None,None,None,F,TK,...,09302016,None,669712185,1.0,20545,NaN,B2,1960-01-01,2016-04-01,None
20,1,20160401.0,TIA,None,G,O,None,M,M,TK,...,09302016,None,2147483647,1.0,20545,20561.0,B2,1960-01-01,2016-04-01,2016-04-17
21,1,20160401.0,TIA,None,G,O,None,M,F,AZ,...,09302016,None,2147483647,608.0,20545,20567.0,B2,1960-01-01,2016-04-01,2016-04-23
22,1,20160401.0,TIA,None,G,O,None,M,M,AZ,...,09302016,None,2147483647,608.0,20545,20575.0,B2,1960-01-01,2016-04-01,2016-05-01
23,1,20160401.0,TIA,None,G,O,None,M,F,TK,...,09302016,None,2147483647,77.0,20545,20574.0,B2,1960-01-01,2016-04-01,2016-04-30
24,1,20160401.0,TIA,None,G,O,None,M,M,OS,...,09302016,None,2147483647,65.0,20545,20554.0,B1,1960-01-01,2016-04-01,2016-04-10
25,1,20160401.0,TIA,None,G,O,None,M,M,OS,...,09302016,None,2147483647,65.0,20545,20562.0,B1,1960-01-01,2016-04-01,2016-04-18
26,1,20160401.0,TIA,None,G,O,None,M,M,TK,...,09302016,None,2147483647,5.0,20545,20580.0,B1,1960-01-01,2016-04-01,2016-05-06
27,1,20160401.0,HLS,None,G,O,None,M,F,AY,...,D/S,None,2147483647,5.0,20545,20665.0,F1,1960-01-01,2016-04-01,2016-07-30
28,1,20160401.0,FLR,None,G,O,None,M,M,AA,...,09302016,None,2147483647,199.0,20545,20572.0,B2,1960-01-01,2016-04-01,2016-04-28
29,1,20160401.0,FLR,None,G,O,None,M,F,AA,...,09302016,None,2147483647,199.0,20545,20572.0,B2,1960-01-01,2016-04-01,2016-04-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,1,20160401.0,None,None,O,I,None,M,None,LH,...,06292016,None,2147483647,438.0,20545,20561.0,WT,1960-01-01,2016-04-01,2016-04-17
71,1,20160401.0,None,None,O,O,None,M,None,BA,...,06292016,None,2147483647,193.0,20545,20560.0,WT,1960-01-01,2016-04-01,2016-04-16
72,1,20160401.0,None,None,G,O,None,M,F,LH,...,06292016,None,2147483647,442.0,20545,20556.0,WT,1960-01-01,2016-04-01,2016-04-12
73,1,20160401.0,None,None,G,I,None,M,F,LH,...,06292016,None,2147483647,442.0,20545,20651.0,WT,1960-01-01,2016-04-01,2016-07-16
74,1,20160401.0,None,None,G,O,None,M,M,LH,...,06292016,None,2147483647,442.0,20545,20549.0,WB,1960-01-01,2016-04-01,2016-04-05
75,1,20160401.0,None,None,G,O,None,M,M,LH,...,06292016,None,2147483647,442.0,20545,20556.0,WT,1960-01-01,2016-04-01,2016-04-12
76,1,20160401.0,None,None,G,O,None,M,F,LH,...,06292016,None,2147483647,442.0,20545,20556.0,WT,1960-01-01,2016-04-01,2016-04-12
77,1,20160401.0,None,None,G,O,None,M,M,LH,...,06292016,None,2147483647,442.0,20545,20556.0,WT,1960-01-01,2016-04-01,2016-04-12
78,1,20160401.0,None,None,G,O,None,M,M,LH,...,06292016,None,2147483647,442.0,20545,20556.0,WT,1960-01-01,2016-04-01,2016-04-12
79,1,20160401.0,None,None,G,O,None,M,M,LH,...,06292016,None,2147483647,442.0,20545,20556.0,WT,1960-01-01,2016-04-01,2016-04-12
80,1,20160401.0,None,None,G,O,None,M,F,LH,...,06292016,None,2147483647,442.0,20545,20558.0,WB,1960-01-01,2016-04-01,2016-04-14
81,1,20160401.0,None,None,G,O,None,M,M,LH,...,06292016,None,2147483647,442.0,20545,20558.0,WB,1960-01-01,2016-04-01,2016-04-14
82,1,20160401.0,None,None,G,O,None,M,M,LH,...,06292016,None,2147483647,402.0,20545,20549.0,WB,1960-01-01,2016-04-01,2016-04-05
83,1,20160401.0,None,None,G,O,None,M,F,OS,...,06292016,None,2147483647,89.0,20545,20567.0,WT,1960-01-01,2016-04-01,2016-04-23
84,1,20160401.0,None,None,G,O,None,M,M,OS,...,06292016,None,2147483647,89.0,20545,20567.0,WT,1960-01-01,2016-04-01,2016-04-23
85,1,20160401.0,None,None,G,O,None,M,F,LH,...,06292016,None,2147483647,402.0,20545,20549.0,WT,1960-01-01,2016-04-01,2016-04-05
86,1,20160401.0,None,None,G,O,None,M,M,LH,...,06292016,None,2147483647,402.0,20545,20549.0,WT,1960-01-01,2016-04-01,2016-04-05
87,1,20160401.0,None,None,G,K,None,M,M,OS,...,06292016,None,2147483647,89.0,20545,20561.0,WT,1960-01-01,2016-04-01,2016-04-17
88,1,20160401.0,None,None,G,O,None,M,F,UA,...,06292016,None,2147483647,31.0,20545,20553.0,WT,1960-01-01,2016-04-01,2016-04-09
89,1,20160401.0,None,None,G,O,None,M,M,OS,...,06292016,None,2147483647,89.0,20545,20553.0,WT,1960-01-01,2016-04-01,2016-04-09
90,1,20160401.0,None,None,G,O,None,M,F,LH,...,06292016,None,2147483647,408.0,20545,20554.0,WT,1960-01-01,2016-04-01,2016-04-10
91,1,20160401.0,None,None,G,O,None,M,M,LH,...,06292016,None,2147483647,408.0,20545,20554.0,WT,1960-01-01,2016-04-01,2016-04-10
92,1,20160401.0,None,None,G,O,None,M,M,OS,...,06292016,None,2147483647,89.0,20545,20568.0,WT,1960-01-01,2016-04-01,2016-04-24
93,1,20160401.0,None,None,G,O,None,M,F,OS,...,06292016,None,2147483647,89.0,20545,20568.0,WT,1960-01-01,2016-04-01,2016-04-24
94,1,20160401.0,None,None,G,O,None,M,F,OS,...,06292016,None,2147483647,89.0,20545,20633.0,WT,1960-01-01,2016-04-01,2016-06-28
95,1,20160401.0,None,None,G,Q,None,M,F,OS,...,06292016,None,2147483647,89.0,20545,20552.0,WT,1960-01-01,2016-04-01,2016-04-08
96,1,20160401.0,None,None,G,None,None,None,F,OS,...,06292016,None,2147483647,89.0,20545,NaN,WT,1960-01-01,2016-04-01,None
97,1,20160401.0,None,None,G,None,None,None,F,LH,...,06292016,None,2147483647,402.0,20545,NaN,WT,1960-01-01,2016-04-01,None
98,1,20160401.0,None,None,G,O,None,M,M,OS,...,06292016,None,2147483647,89.0,20545,20547.0,WT,1960-01-01,2016-04-01,2016-04-03
99,1,20160401.0,None,None,G,O,None,M,M,OS,...,06292016,None,2147483647,89.0,20545,20547.0,WT,1960-01-01,2016-04-01,2016-04-03

In [20]:
df_i94.select('i94bir').toPandas().describe()

             i94bir
count  3.095511e+06
mean   4.176761e+01
std    1.742026e+01
min   -3.000000e+00
25%    3.000000e+01
50%    4.100000e+01
75%    5.400000e+01
max    1.140000e+02

In [21]:
for col in df_i94_clean.columns:
    print("\n",col)
    print(df_i94_clean.select(col).distinct().show(50))

 count
+-----+
|count|
+-----+
|    1|
+-----+

None

 dtadfile
+--------+
|dtadfile|
+--------+
|20160916|
|20160524|
|20160706|
|20160404|
|20160423|
|20160618|
|20160502|
|20160518|
|20160526|
|20160516|
|20160615|
|20160522|
|20160826|
|20160512|
|20160815|
|20160831|
|20160606|
|20160702|
|20160414|
|20160801|
|20160901|
|    null|
|20160528|
|20160521|
|20160506|
|20160523|
|20160603|
|20160630|
|20160505|
|20160829|
|20160426|
|20160531|
|20160509|
|20160529|
|20160424|
|20160709|
|20160608|
|20160720|
|20160525|
|20160909|
|20160422|
|20160729|
|20160816|
|20160508|
|20160514|
|20160823|
|20160824|
|20160421|
|20160420|
|20160430|
+--------+
only showing top 50 rows

None

 visapost
+--------+
|visapost|
+--------+
|     CRS|
|     KGL|
|     AKD|
|     BGM|
|     TRK|
|     MOR|
|     MDL|
|     KAT|
|     FRN|
|     CJT|
|     MBO|
|     OSK|
|     LND|
|     SNA|
|     MXT|
|     CLG|
|     BRA|
|     SPM|
|     ZZZ|
|     GRB|
|     NGL|
|     CAR|
|     MDD|
|     TKY|
|     TEG|
|     KRK|
|     SPL|
|     ABS|
|     NAS|
|     POZ|
|     MDR|
|     ALG|
|     FTN|
|     IST|
|     BRN|
|     CPC|
|     MDN|
|     WAR|
|     KNG|
|     OTT|
|     CRY|
|     JOH|
|     NUK|
|     QUE|
|     OUA|
|     ESC|
|     RCF|
|     DET|
|     BDT|
|     SNS|
+--------+
only showing top 50 rows

None

 occup
+-----+
|occup|
+-----+
|  PHA|
|  ENT|
|  REL|
|  ACH|
|  101|
|  EMM|
|  ULS|
|  GEN|
|  DVM|
|  MTH|
|  SVC|
|  ECH|
|  EXA|
|  ENV|
|  ENP|
|  PRF|
|  VOC|
| null|
|  AST|
|  TCH|
|  MSC|
|  HFM|
|  ACN|
|  ORS|
|  300|
|  HSW|
|  TCC|
|  ECO|
|  PRD|
|  ATH|
|  LAC|
|  PHR|
|  NAW|
|  999|
|  ADM|
|  EAS|
|  PPS|
|  UNP|
|  PRS|
|  ECV|
|  HEH|
|  SLS|
|  MCH|
|  RPT|
|  CPA|
|  AGR|
|  L1M|
|  TTP|
|  LLJ|
|  WTR|
+-----+
only showing top 50 rows

None

 entdepa
+-------+
|entdepa|
+-------+
|      K|
|      F|
|   null|
|      T|
|      B|
|      M|
|      U|
|      O|
|      Z|
|      A|
|      N|
|      G|
|      P|
|      H|
+-------+

None

 entdepd
+-------+
|entdepd|
+-------+
|      K|
|      Q|
|   null|
|      M|
|      L|
|      V|
|      O|
|      D|
|      J|
|      N|
|      W|
|      R|
|      I|
+-------+

None

 entdepu
+-------+
|entdepu|
+-------+
|   null|
|      Y|
|      U|
+-------+

None

 matflag
+-------+
|matflag|
+-------+
|   null|
|      M|
+-------+

None

 gender
+------+
|gender|
+------+
|     F|
|  null|
|     M|
|     U|
|     X|
+------+

None

 airline
+-------+
|airline|
+-------+
|     LT|
|     MM|
|     DZ|
|     CI|
|    447|
|    YFA|
|     TC|
|     AZ|
|     FI|
|    R0E|
|    B01|
|    78B|
|     UA|
|     EA|
|     Q7|
|     VP|
|    FYG|
|    CHP|
|    743|
|     3M|
|     15|
|     KI|
|    635|
|     LA|
|     D5|
|     SB|
|     BW|
|     FC|
|     TB|
|    YNT|
|     BS|
|     PZ|
|     NK|
|    009|
|    P2P|
|     OI|
|     4O|
|     XL|
|    DPJ|
|    D0S|
|    XLA|
|    351|
|     AM|
|     PS|
|    HPJ|
|     PL|
|     AA|
|    0BA|
|    TOS|
|    0FR|
+-------+
only showing top 50 rows

None

 cic_id
+------+
|cic_id|
+------+
|   148|
|   463|
|   471|
|   496|
|   833|
|  1088|
|  1238|
|  1342|
|  1580|
|  1591|
|  1645|
|  1829|
|  1959|
|  2122|
|  2142|
|  2366|
|  2866|
|  3175|
|  3749|
|  3794|
|  4101|
|  4519|
|  4818|
|  4900|
|  4935|
|  5156|
|  5300|
|  5518|
|  6336|
|  6357|
|  6397|
|  6466|
|  6620|
|  6654|
|  6658|
|  7240|
|  7253|
|  7340|
|  7554|
|  7754|
|  8086|
|  8389|
|  8592|
|  8638|
|  9376|
|  9427|
|  9465|
|  9852|
|  9900|
| 10817|
+------+
only showing top 50 rows

None

 year
+----+
|year|
+----+
|2016|
+----+

None

 month
+-----+
|month|
+-----+
|    4|
+-----+

None

 country_birth_id
+----------------+
|country_birth_id|
+----------------+
|             148|
|             392|
|             516|
|             251|
|             580|
|             255|
|             133|
|             296|
|             472|
|             513|
|             322|
|             375|
|             108|
|             155|
|             368|
|             101|
|             115|
|             126|
|             756|
|             385|
|             412|
|             406|
|             688|
|             332|
|             577|
|             384|
|             159|
|             743|
|             253|
|             103|
|             236|
|             329|
|             336|
|             350|
|             388|
|             417|
|             602|
|             578|
|             333|
|             601|
|             128|
|             209|
|             372|
|             727|
|             330|
|             122|
|             157|
|             111|
|             519|
|             140|
+----------------+
only showing top 50 rows

None

 country_residence_id
+--------------------+
|country_residence_id|
+--------------------+
|                 392|
|                 243|
|                 516|
|                 251|
|                 255|
|                 296|
|                 472|
|                 322|
|                 513|
|                 321|
|                 375|
|                 108|
|                 155|
|                 368|
|                 101|
|                 115|
|                 126|
|                 385|
|                 412|
|                 688|
|                 723|
|                 577|
|                 332|
|                 384|
|                 159|
|                 743|
|                 271|
|                 253|
|                 103|
|                 236|
|                 329|
|                 350|
|                 336|
|                 602|
|                 388|
|                 417|
|                 409|
|                 333|
|                 601|
|                 209|
|                 604|
|                 128|
|                 372|
|                 330|
|                 122|
|                 157|
|                 346|
|                 111|
|                 519|
|                 140|
+--------------------+
only showing top 50 rows

None

 port_code
+---------+
|port_code|
+---------+
|      FMY|
|      BGM|
|      HEL|
|      DNS|
|      MOR|
|      FOK|
|      HVR|
|      SNA|
|      PTK|
|      SPM|
|      CLG|
|      OPF|
|      DLB|
|      ABS|
|      NAS|
|      MYR|
|      PVD|
|      OAK|
|      FAR|
|      OTT|
|      PBB|
|      WAR|
|      CRY|
|      NRN|
|      DET|
|      FRT|
|      NOO|
|      REN|
|      BEE|
|      AGN|
|      FAL|
|      MTH|
|      AGA|
|      NRT|
|      OTM|
|      ROS|
|      BWM|
|      LEX|
|      NSV|
|      RIF|
|      SFR|
|      ADW|
|      VCV|
|      COB|
|      RAY|
|      JFA|
|      BHX|
|      GPM|
|      SAV|
|      LLB|
+---------+
only showing top 50 rows

None

 transport_mode_code
+-------------------+
|transport_mode_code|
+-------------------+
|               null|
|                  1|
|                  3|
|                  9|
|                  2|
+-------------------+

None

 state_code
+----------+
|state_code|
+----------+
|        .N|
|        RG|
|        YH|
|        RF|
|        FT|
|        CI|
|        TC|
|        SC|
|        AZ|
|        FI|
|        IC|
|        PU|
|        UA|
|        EA|
|        NS|
|        KI|
|        RO|
|        PI|
|        SL|
|        LA|
|        YN|
|        NL|
|        MN|
|        BS|
|        FC|
|        BW|
|        11|
|        NK|
|        OI|
|        RE|
|        PS|
|        PL|
|        AM|
|        AA|
|        MK|
|        NJ|
|        DR|
|        73|
|        RA|
|        WC|
|        MX|
|        HW|
|         3|
|        30|
|        JF|
|         F|
|        VL|
|        DC|
|        QL|
|        TV|
+----------+
only showing top 50 rows

None

 age
+----+
| age|
+----+
|  31|
|  85|
|  65|
|  53|
|  78|
| 108|
|  34|
| 101|
|  81|
|  28|
|  76|
|  27|
|  26|
|  44|
| 103|
|  12|
|  91|
|  22|
|  93|
| 111|
|  47|
|null|
|   1|
|  52|
|  13|
|  16|
|   6|
|  86|
|   3|
|  20|
|  40|
|  94|
|  57|
|  54|
|  96|
|  48|
|   5|
|  19|
|  92|
|  64|
|  41|
|  43|
|  15|
|  37|
|  61|
|  88|
| 107|
|  17|
|   9|
|  72|
+----+
only showing top 50 rows

None

 visa_code
+---------+
|visa_code|
+---------+
|        1|
|        3|
|        2|
+---------+

None

 birth_year

+----------+
|birth_year|
+----------+
|      1959|
|      1990|
|      1975|
|      1977|
|      1924|
|      2003|
|      2007|
|      1974|
|      2015|
|      1927|
|      1955|
|      2006|
|      1978|
|      1925|
|      1908|
|      1961|
|      2013|
|      1942|
|      1939|
|      1944|
|      null|
|      1902|
|      1922|
|      1952|
|      1956|
|      1934|
|      1988|
|      1997|
|      1994|
|      1968|
|      2014|
|      1917|
|      1951|
|      1930|
|      1938|
|      1973|
|      1979|
|      1946|
|      1947|
|      2019|
|      1971|
|      1950|
|      1913|
|      1966|
|      1949|
|      2004|
|      1991|
|      1967|
|      1969|
|      1982|
+----------+
only showing top 50 rows

None

 allowed_to_stay_until
+---------------------+
|allowed_to_stay_until|
+---------------------+
|             09282016|
|             02282017|
|             10202017|
|             11292017|
|             11162016|
|             01102017|
|             06152016|
|             03152017|
|             03262017|
|             11142016|
|             01192018|
|             04102016|
|             07032016|
|             07202019|
|             06082019|
|             05232016|
|             08042016|
|             03292017|
|             04082018|
|             08042017|
|             08262016|
|             08102016|
|             08052017|
|             02182018|
|             01032018|
|             10172017|
|             11022016|
|             09062017|
|             05042016|
|             07122016|
|             05092017|
|             10182016|
|             04232017|
|             09262016|
|             03192017|
|             10102017|
|             04152018|
|             01092017|
|             03092018|
|             11052017|
|             02052018|
|             06192017|
|             04122018|
|             07142019|
|             09062016|
|             05072016|
|             10242016|
|             03072017|
|             03012018|
|             10312016|
+---------------------+
only showing top 50 rows

None

 ins_num
+-------+
|ins_num|
+-------+
|   5325|
|   3414|
|   7252|
|   4032|
|   3959|
|  39645|
|  39590|
|    691|
|  39458|
|   4821|
|   5023|
|   3517|
|   5149|
|   3441|
|   5067|
|   3281|
|   3826|
|  38900|
|   3650|
|   1669|
|   3368|
|   2393|
|   4894|
|   4838|
|   1808|
|   1746|
|   3526|
|   5181|
|   5044|
|   7208|
|   4850|
|   3949|
|   2696|
| 368006|
|   2700|
| 393306|
|   2530|
|   5057|
|   3652|
|   4665|
|   5234|
|   2930|
|   1903|
|   2550|
|   3993|
|   6758|
|   5048|
|   3895|
|    475|
|   3902|
+-------+
only showing top 50 rows

None

 admission_num
+-------------+
|admission_num|
+-------------+
|    667627785|
|    666638685|
|    666771585|
|    667309685|
|    665931985|
|    668631485|
|    666193085|
|    666735885|
|    665171085|
|    665928185|
|    664814485|
|    667616785|
|    672259685|
|    672209185|
|    672424685|
|    670914985|
|    670028485|
|    669876285|
|    672141385|
|    672701485|
|    673709885|
|    676016085|
|    674581585|
|    674129685|
|    674500985|
|    676482785|
|    673717085|
|    673710785|
|    674352385|
|    679808385|
|    678532385|
|    679975185|
|    679772685|
|    679312485|
|    679156685|
|    678314185|
|    678023685|
|    680749885|
|    680573885|
|    679137385|
|    678236285|
|    681825085|
|    682166085|
|    682443885|
|    681078985|
|    680253985|
|    684185485|
|    681445585|
|    680426185|
|    682266985|
+-------------+
only showing top 50 rows

None

 flight_num
+----------+
|flight_num|
+----------+
|       148|
|      8086|
|      1238|
|       463|
|      5803|
|      1645|
|      4900|
|      4818|
|      1088|
|      2142|
|      9465|
|      1829|
|      1342|
|      8638|
|       471|
|       833|
|      1896|
|       623|
|       858|
|       392|
|      1460|
|       737|
|      4161|
|       540|
|      1025|
|       243|
|      2387|
|      3475|
|      4190|
|       897|
|     18201|
|      1721|
|      1483|
|      2811|
|     32891|
|      1507|
|      3698|
|        31|
|      1618|
|      1322|
|      1352|
|      1903|
|       516|
|      2572|
|      4391|
|      5345|
|      1270|
|      1650|
|      2776|
|      7387|
+----------+
only showing top 50 rows

None

 arrival_date_sas
+----------------+
|arrival_date_sas|
+----------------+
|           20554|
|           20573|
|           20574|
|           20555|
|           20571|
|           20559|
|           20565|
|           20550|
|           20561|
|           20569|
|           20553|
|           20548|
|           20560|
|           20572|
|           20566|
|           20552|
|           20567|
|           20545|
|           20547|
|           20551|
|           20564|
|           20563|
|           20546|
|           20549|
|           20556|
|           20557|
|           20562|
|           20568|
|           20558|
|           20570|
+----------------+

None

 departure_from_usa_sas
+----------------------+
|departure_from_usa_sas|
+----------------------+
|                 20683|
|                 20596|
|                 20467|
|                 20624|
|                 20671|
|                 20542|
|                 20674|
|                 20631|
|                 20223|
|                 20554|
|                 20642|
|                 20672|
|                 20540|
|                 45427|
|                 20595|
|                 20653|
|                 20693|
|                 20688|
|                 20238|
|                 20583|
|                 20573|
|                 20666|
|                 20575|
|                 20696|
|                 20651|
|                 20656|
|                 20643|
|                 20607|
|                 20538|
|                 20459|
|                 20712|
|                 20578|
|                 20663|
|                 20613|
|                 20628|
|                 20702|
|                 20574|
|                 20555|
|                 20700|
|                 20644|
|                 20658|
|                 20602|
|                 20637|
|                 39935|
|                 20709|
|                 20662|
|                 20622|
|                 20201|
|                 20625|
|                 20604|
+----------------------+
only showing top 50 rows

None

 visa_type
+---------+
|visa_type|
+---------+
|       F2|
|      GMB|
|       B2|
|       F1|
|      CPL|
|       I1|
|       WB|
|       M1|
|       B1|
|       WT|
|       M2|
|       CP|
|      GMT|
|       E1|
|        I|
|       E2|
|      SBP|
+---------+

None

 date_baseline
+-------------+
|date_baseline|
+-------------+
|   1960-01-01|
+-------------+

None

 arrival_date
+------------+
|arrival_date|
+------------+
|  2016-04-25|
|  2016-04-22|
|  2016-04-30|
|  2016-04-26|
|  2016-04-04|
|  2016-04-16|
|  2016-04-18|
|  2016-04-11|
|  2016-04-29|
|  2016-04-19|
|  2016-04-14|
|  2016-04-08|
|  2016-04-02|
|  2016-04-20|
|  2016-04-13|
|  2016-04-09|
|  2016-04-17|
|  2016-04-01|
|  2016-04-07|
|  2016-04-12|
|  2016-04-03|
|  2016-04-15|
|  2016-04-28|
|  2016-04-24|
|  2016-04-23|
|  2016-04-05|
|  2016-04-06|
|  2016-04-21|
|  2016-04-10|
|  2016-04-27|
+------------+

None

 departure_from_usa
+------------------+
|departure_from_usa|
+------------------+
|        2016-03-01|
|        2016-04-25|
|        2016-05-03|
|        2016-08-31|
|        2016-07-26|
|        2016-08-15|
|        2016-07-17|
|        2016-07-03|
|        2016-08-23|
|        2016-06-02|
|        2016-05-26|
|        2016-02-04|
|        2016-01-13|
|        2016-04-22|
|        2016-06-16|
|        2069-05-03|
|        2016-05-09|
|        2016-07-19|
|        2016-09-15|
|        2016-05-23|
|        2016-08-26|
|        2016-03-25|
|        2016-08-01|
|        2016-09-09|
|        2016-06-17|
|        2016-08-16|
|        2016-04-30|
|        2016-07-21|
|        2016-05-27|
|        2016-07-02|
|        2016-08-06|
|        2016-05-07|
|        2016-08-05|
|        2016-04-26|
|        2016-05-13|
|        2016-05-31|
|        2015-04-18|
|        2016-08-20|
|        2016-09-05|
|        2016-05-21|
|        2015-04-08|
|        2016-05-11|
|        2016-06-22|
|        2015-05-18|
|        2016-05-28|
|        2016-06-19|
|        2016-03-11|
|        2016-03-27|
|        2016-06-08|
|              null|
+------------------+
only showing top 50 rows

None

In [22]:
print(df_i94.select('insnum').distinct().show(1000))

+------+
|insnum|
+------+
|  5325|
|  3414|
|  7252|
|  4032|
|  3959|
| 39645|
| 39590|
|   691|
| 39458|
|  4821|
|  5023|
|  3517|
|  5149|
|  3441|
|  5067|
|  3281|
|  3826|
| 38900|
|  3650|
|  1669|
|  3368|
|  2393|
|  4894|
|  4838|
|  1808|
|  1746|
|  3526|
|  5181|
|  5044|
|  7208|
|  4850|
|  3949|
|  2696|
|368006|
|  2700|
|393306|
|  2530|
|  5057|
|  3652|
|  4665|
|  5234|
|  2930|
|  1903|
|  2550|
|  3993|
|  6758|
|  5048|
|  3895|
|   475|
|  3902|
|  3898|
| 17274|
|  5543|
|  4736|
|  4719|
|  5071|
|  7829|
|  4672|
|  5434|
|  2495|
|  3875|
| 36956|
| 39821|
|  8691|
|  4690|
|  4782|
|  4818|
|  7353|
|  1104|
|  3656|
|  5104|
|  3250|
|  4685|
|  2392|
|  4333|
|  3891|
|  3641|
|  2964|
|  4315|
|  3365|
|  4789|
|  2144|
|  1435|
|  5306|
|  3953|
|  4856|
|  3661|
|  2953|
| 39368|
|  7980|
|   383|
|  3454|
|  5170|
|  8682|
|  5412|
|  5179|
|  5096|
|  3983|
|  6952|
|  3863|
| 39868|
|  2436|
|KITAMU|
|  5041|
|  4884|
|  4403|
|  3967|
|  4369|
|  5426|
|  3808|
|  4437|
| 36890|
|  2762|
|  2363|
|  2138|
|  5059|
|  3884|
|  2115|
|  9680|
|  4546|
|  0031|
|   388|
|366306|
|398506|
|  5458|
|  5101|
|  7799|
|  5045|
|  3521|
|  7702|
|  1093|
|  2354|
|5282OK|
|  2683|
| 39697|
|  3742|
| 39475|
|  5060|
|  3709|
|   685|
|  6846|
|  3728|
|  3660|
|   387|
|   361|
|  4738|
|  4765|
|  4638|
|  4977|
|  3406|
|  2443|
|  2201|
|  2846|
|  7584|
|  3546|
| 39890|
|   703|
|  3268|
|  3802|
|  5473|
|  3550|
|  3933|
| 36891|
|  3922|
|  2587|
|  5213|
|  6877|
|  4595|
|  1526|
|   468|
|  3583|
|  3716|
|  4953|
|  3582|
|  4370|
|  2031|
|  4631|
|  1673|
|  4584|
|  3646|
| 26Y82|
| 39491|
|  3914|
|  4837|
|  4817|
|   512|
|  3745|
|  5092|
|  2699|
|  5072|
|  3662|
|  3978|
|  3952|
|     3|
| 37025|
| 20883|
|  2090|
|  5064|
|  1215|
|  4130|
|  4823|
|  2026|
|  5415|
|  3615|
|  3988|
| 36614|
|  3597|
| 35833|
|  4117|
|  3944|
|  3889|
| 36632|
| 39780|
|  2778|
|  5017|
|  4358|
|  4942|
|  3058|
|  3794|
|  3316|
|  5226|
|  4341|
|  1477|
|  4510|
|  5413|
| DUFFY|
|  4887|
|  3559|
|SJOHNS|
|  4593|
|  3833|
|   895|
|   365|
| 36952|
|  5280|
|  3720|
|  3468|
|  4717|
|  3060|
|  7351|
|  4278|
|  3148|
|  2113|
|  7233|
|DSDAVI|
|  0180|
|  7814|
|  2385|
|  3727|
|  1530|
|397105|
|  3927|
|  3087|
|  8683|
|  3544|
|  1911|
|  4791|
|  4995|
|  7824|
|  7207|
|  3935|
|  5022|
|  7805|
|  4701|
|  3452|
|  1882|
|  3723|
|  4819|
|  4681|
|  1821|
| 39680|
| 36698|
|  5326|
|  4054|
|  7261|
|  2323|
|  3981|
|   692|
|  5421|
|  4271|
|  5464|
|  4196|
|  4080|
|  3506|
| 36781|
|419551|
|  6801|
|  3327|
|  7473|
|  4104|
|  3541|
|  1062|
|  5034|
|  5366|
|  5437|
|  1794|
|  5407|
| 14939|
| 34343|
|  3682|
|  4972|
|  2685|
|   343|
|  4833|
|  2013|
|  2774|
|  4912|
|  4979|
|  3936|
|  3630|
|   663|
|  3080|
|  3801|
|  3565|
|   JLE|
|  3726|
|  4925|
|  5303|
|  5538|
|  2282|
|WILLIA|
|  1722|
|  1013|
|  3663|
|  4582|
|  3879|
|  3084|
|  4693|
|  3509|
|  3605|
|  4653|
|  5469|
|  4989|
|  4930|
|  4086|
|  1711|
| 38921|
|  3649|
|   973|
| 38855|
|  1405|
|  4748|
| 39710|
|388504|
|  6899|
|  3181|
|  2303|
|  5240|
|  3666|
|  6945|
|  3691|
|  4562|
|367905|
|     0|
|  5053|
|  5192|
|  5359|
|  2703|
|  3702|
|  3911|
| 38980|
|393905|
|   060|
|  2588|
|  5116|
|  3747|
|  4317|
|  2375|
| 35888|
|  5190|
|  1962|
|  3797|
|  3360|
|   K88|
|  1841|
|  1416|
|  4300|
|  1340|
|  3551|
|  5152|
|  4769|
|  1549|
|    99|
| 72636|
| 38812|
|368606|
|  4609|
|  3627|
|  5482|
|  4929|
|  2131|
|  5308|
|  4414|
|464006|
|072716|
|  4608|
| 36800|
|  3670|
|  3947|
|  1954|
|  4539|
|  7401|
|  3771|
|354170|
|  2811|
|  0986|
|  5282|
|  4702|
|  4323|
|  2396|
|  2823|
|  3527|
|  4699|
|  3622|
|  4667|
|  3672|
|  4652|
|  1721|
|  3860|
|  3883|
|  3976|
|  3653|
| T3692|
|  3958|
| T3980|
|  null|
|  1544|
|  4204|
|  5286|
|  4242|
|  4723|
|  3809|
|  4682|
| T3675|
|  1145|
|  5457|
|  5037|
|  4506|
|  7255|
|  7329|
|  3665|
|  3692|
|  2693|
|  3031|
|  1278|
|  4806|
|  4508|
|  3328|
|  2377|
|  4256|
|  5156|
|     T|
|   953|
|  4646|
|  0672|
|  4444|
|  4243|
|  3904|
|  3463|
|  6962|
|  3729|
|  2028|
|  5275|
|  5142|
|  5432|
|  4843|
|  5527|
|  3960|
| 39546|
|  4879|
|  1753|
|  5398|
| 36668|
|  2442|
|  3867|
|  4661|
|  4731|
|  4892|
|  5349|
|  3618|
|  3852|
|  3724|
|  4686|
|    GG|
|  3558|
|  2091|
|  3738|
|  4721|
|  8558|
|  3633|
|   300|
| 72938|
|  4901|
|  5261|
|  3855|
|  3946|
|  4547|
|  3931|
|  3600|
|     5|
|369705|
|  3068|
|  3389|
|  4148|
|  1861|
|  3172|
|  4986|
|  4792|
|  7875|
|  5183|
|  5069|
|  7890|
|  4237|
| 36700|
|  8943|
|  4071|
|  5189|
|  3676|
|  4247|
|  2775|
|  4615|
|  4954|
|  2831|
|  7321|
|  5536|
|  3892|
| 33934|
|  1874|
|  2437|
|  1254|
|  5384|
|  7439|
|  5030|
|  5267|
|  4617|
|  3876|
|  3905|
|  3523|
|  4431|
|  4759|
|  4809|
|  4767|
|  5087|
|  2099|
| 50347|
| 36564|
|  4796|
|  5120|
|  4512|
|  1052|
| T3945|
| 39743|
| 38901|
|  3221|
|  3674|
|  2077|
|  4928|
|  7878|
|  4762|
|  4557|
|  3955|
|  3113|
|  5233|
|  4159|
|  2371|
|  2365|
|  4201|
|  4576|
|  5010|
|   PJM|
|  5028|
|  7237|
|  3213|
|  2935|
| 36714|
|  6966|
|070416|
|  3333|
|  5036|
|  5042|
|  5117|
|  5187|
|  3982|
|  3790|
|  3002|
| 36954|
|  3534|
|  6938|
|  2892|
|  4133|
|  1421|
|  5258|
|  1845|
|  3482|
|  3693|
| 33884|
|  7863|
|  4756|
|  3980|
|  1809|
|  1550|
|  5340|
|351507|
|  5063|
|  4606|
|  5243|
|  3451|
|  1792|
|  6425|
|  2833|
|  4037|
|  4461|
|  3609|
|  3539|
|  3640|
|  1822|
|  4445|
|  4644|
|  5307|
|  3511|
|  5230|
|  5418|
|  3939|
| 39763|
|  2441|
|LMATTE|
|  1453|
|  4712|
|  3536|
|  5040|
|  5137|
|  4640|
|  1964|
|  0795|
|010719|
|  2802|
|  4404|
|  4968|
|  5102|
|  2340|
|  5191|
|  3433|
|  3021|
|  3997|
|  3864|
|309305|
|366606|
|  7051|
|  3305|
| 02346|
|  4940|
|  1551|
|  4931|
| 33663|
| G3974|
|  3923|
|  4868|
|  5107|
|  5467|
|  5257|
|  3930|
|  5215|
|  4552|
| 36914|
|  3987|
|  2710|
| 72840|
|  6944|
|  3038|
|  4111|
|  1559|
|  4775|
|  2744|
|    GB|
|    FH|
|  4060|
|  2376|
|  4859|
|  7506|
| 36821|
| Y3980|
|  3610|
|  7478|
|  5521|
|  3518|
|  4364|
|  5519|
|  3868|
| 36703|
|  1899|
|  5454|
|  3566|
|  3576|
|  4696|
|  7567|
|  7834|
|  3882|
|  7898|
|  2971|
|  2933|
|   375|
|393105|
|  1854|
|  5441|
|  4312|
|  7853|
|  5427|
|  1243|
|   455|
|366006|
|369706|
|  5400|
|  5444|
|  2719|
|  7046|
|  1288|
|  5091|
|  3699|
|  5178|
|  3984|
|  5480|
|  7893|
|  5058|
|  1339|
|  5051|
|  5289|
|  4555|
| T3693|
| T3688|
| 38925|
|  0910|
|  4314|
|  5151|
|  3160|
|  3560|
|  4498|
| 39700|
|  4639|
|  2925|
|  2075|
|  4860|
|  7361|
|  5049|
|  6813|
|  1921|
|  4567|
|  3669|
|052316|
|  3871|
|  2940|
|  3039|
|  3903|
|  3788|
|  4226|
|  5032|
|    DE|
|  5246|
|  7363|
|  2745|
|  4436|
|     6|
|  4126|
|  2667|
|  2666|
|  4550|
| 38712|
|   385|
|  1820|
|  3503|
|  1414|
|  4926|
|  5145|
|  4827|
|  5056|
|  4537|
|  3183|
|  3159|
|   E36|
| 36633|
|  3962|
|   932|
| 39555|
|  3865|
|369106|
| T3987|
|  3301|
|  2695|
|  3415|
|  4713|
|  3460|
|  4973|
|369369|
|  4694|
|545507|
|  4781|
|  2843|
|  4173|
|  4677|
|  4964|
|   AMS|
|  3995|
|393205|
|  2952|
|  4970|
|  4899|
|  1402|
|  3487|
|  3295|
|  7235|
|  5532|
|  3877|
|  2311|
|  5144|
|  5203|
|  4680|
|  4307|
|  4347|
|  3535|
|  2494|
|  5277|
|  5318|
|  2687|
|  2797|
|  7578|
|  4085|
|  1566|
|  4706|
|  2213|
|  3599|
|  3954|
|   UNL|
|  3850|
| 33939|
|  4656|
|  2297|
|  3330|
|  3585|
|  3963|
|  0221|
| 36573|
|  3608|
| T3950|
| 36980|
|  3540|
|  3603|
|  5416|
|  4785|
|  1875|
|  4556|
|  7847|
|  3278|
|  5342|
|  2768|
|  4784|
|  3174|
|  1967|
|  4842|
|  3739|
|  3459|
|  5529|
|  4502|
| 36854|
|  2661|
|  6244|
|   347|
|  4128|
|  4641|
|  4779|
|  7525|
|  4551|
|  3689|
|  5168|
|  4981|
|  3323|
|  2782|
|  3828|
|  3896|
|  3921|
|  3951|
| 33675|
|  4697|
|  4231|
|  3157|
|  2373|
|  3780|
|  4290|
|  1924|
|  5483|
|  4596|
|  3945|
|  4616|
| 36964|
|  7394|
|    KR|
|  5417|
|  2899|
|  3237|
|   E13|
|  4811|
|  4571|
|  2198|
|  4711|
|  1396|
|  3667|
| 36910|
|  7821|
|  4900|
|  4763|
|  4739|
|  7419|
|  6837|
|  3659|
|  1422|
|   UNK|
|  2582|
|  2869|
|  2982|
|  2682|
|  7218|
|  4349|
|  0938|
|  4780|
|  5420|
|  5803|
| 36825|
|  3390|
|  4041|
|  4788|
|  3568|
|  3485|
|  3035|
| BROWN|
|  1939|
|  5118|
|  5248|
|  4916|
|  3940|
|  7397|
| 39843|
|  3032|
|  2493|
|  4022|
|  5055|
|  4285|
|  5542|
|  2116|
|  4915|
|  7844|
|    AL|
|  3791|
|  3894|
|  3881|
|  3975|
|  3081|
|  3022|
|  2581|
|  4505|
|  5025|
|  4773|
|  4602|
|  7658|
|  3655|
| Y3665|
| Y3940|
|  4238|
| 39920|
|  4327|
|  2391|
|  7288|
|  4493|
|  3658|
|  4689|
|  4858|
|  1716|
|  4101|
|  2066|
|  7895|
|  7253|
|  1451|
|  3924|
|  4647|
|  5276|
|  6930|
|130920|
| T3685|
|  1839|
|  4745|
|  1852|
|  1802|
|  3880|
| 16555|
|  3899|
|  3763|
| 38787|
|  3053|
|   369|
|  3079|
| 36Y82|
|  6578|
|  1667|
+------+
only showing top 1000 rows

None

In [23]:
df_i94.show(20)

+-----+------+------+------+------+-------+-------+-------+-------+-------+------+-------+-----+--------+--------+-----+-------+-------+-------+-------+-------+--------+------+------+-------+--------------+-----+--------+
|cicid| i94yr|i94mon|i94cit|i94res|i94port|arrdate|i94mode|i94addr|depdate|i94bir|i94visa|count|dtadfile|visapost|occup|entdepa|entdepd|entdepu|matflag|biryear| dtaddto|gender|insnum|airline|        admnum|fltno|visatype|
+-----+------+------+------+------+-------+-------+-------+-------+-------+------+-------+-----+--------+--------+-----+-------+-------+-------+-------+-------+--------+------+------+-------+--------------+-----+--------+
|  6.0|2016.0|   4.0| 692.0| 692.0|    XXX|20573.0|   null|   null|   null|  37.0|    2.0|  1.0|    null|    null| null|      T|   null|      U|   null| 1979.0|10282016|  null|  null|   null| 1.897628485E9| null|      B2|
|  7.0|2016.0|   4.0| 254.0| 276.0|    ATL|20551.0|    1.0|     AL|   null|  25.0|    3.0|  1.0|20130811|     SEO| null|      G|   null|      Y|   null| 1991.0|     D/S|     M|  null|   null|  3.73679633E9|00296|      F1|
| 15.0|2016.0|   4.0| 101.0| 101.0|    WAS|20545.0|    1.0|     MI|20691.0|  55.0|    2.0|  1.0|20160401|    null| null|      T|      O|   null|      M| 1961.0|09302016|     M|  null|     OS|  6.66643185E8|   93|      B2|
| 16.0|2016.0|   4.0| 101.0| 101.0|    NYC|20545.0|    1.0|     MA|20567.0|  28.0|    2.0|  1.0|20160401|    null| null|      O|      O|   null|      M| 1988.0|09302016|  null|  null|     AA|9.246846133E10|00199|      B2|
| 17.0|2016.0|   4.0| 101.0| 101.0|    NYC|20545.0|    1.0|     MA|20567.0|   4.0|    2.0|  1.0|20160401|    null| null|      O|      O|   null|      M| 2012.0|09302016|  null|  null|     AA|9.246846313E10|00199|      B2|
| 18.0|2016.0|   4.0| 101.0| 101.0|    NYC|20545.0|    1.0|     MI|20555.0|  57.0|    1.0|  1.0|20160401|    null| null|      O|      O|   null|      M| 1959.0|09302016|  null|  null|     AZ|9.247103803E10|00602|      B1|
| 19.0|2016.0|   4.0| 101.0| 101.0|    NYC|20545.0|    1.0|     NJ|20558.0|  63.0|    2.0|  1.0|20160401|    null| null|      O|      K|   null|      M| 1953.0|09302016|  null|  null|     AZ|9.247139923E10|00602|      B2|
| 20.0|2016.0|   4.0| 101.0| 101.0|    NYC|20545.0|    1.0|     NJ|20558.0|  57.0|    2.0|  1.0|20160401|    null| null|      O|      K|   null|      M| 1959.0|09302016|  null|  null|     AZ|9.247161383E10|00602|      B2|
| 21.0|2016.0|   4.0| 101.0| 101.0|    NYC|20545.0|    1.0|     NY|20553.0|  46.0|    2.0|  1.0|20160401|    null| null|      O|      O|   null|      M| 1970.0|09302016|  null|  null|     AZ|9.247079603E10|00602|      B2|
| 22.0|2016.0|   4.0| 101.0| 101.0|    NYC|20545.0|    1.0|     NY|20562.0|  48.0|    1.0|  1.0|20160401|    null| null|      O|      O|   null|      M| 1968.0|09302016|  null|  null|     AZ|9.247848973E10|00608|      B1|
| 23.0|2016.0|   4.0| 101.0| 101.0|    NYC|20545.0|    1.0|     NY|20671.0|  52.0|    2.0|  1.0|20160401|    null| null|      O|      O|   null|      M| 1964.0|09302016|  null|  null|     TK|9.250139443E10|00001|      B2|
| 24.0|2016.0|   4.0| 101.0| 101.0|    TOR|20545.0|    1.0|     MO|20554.0|  33.0|    2.0|  1.0|20160401|    null| null|      O|      O|   null|      M| 1983.0|09302016|  null|  null|     MQ|9.249090503E10|03348|      B2|
| 27.0|2016.0|   4.0| 101.0| 101.0|    BOS|20545.0|    1.0|     MA|20549.0|  58.0|    1.0|  1.0|20160401|     TIA| null|      G|      O|   null|      M| 1958.0|04062016|     M|  null|     LH|9.247876383E10|00422|      B1|
| 28.0|2016.0|   4.0| 101.0| 101.0|    ATL|20545.0|    1.0|     MA|20549.0|  56.0|    1.0|  1.0|20160401|     TIA| null|      G|      O|   null|      M| 1960.0|04062016|     F|  null|     LH|9.247890033E10|00422|      B1|
| 29.0|2016.0|   4.0| 101.0| 101.0|    ATL|20545.0|    1.0|     MA|20561.0|  62.0|    2.0|  1.0|20160401|     TIA| null|      G|      O|   null|      M| 1954.0|09302016|     M|  null|     AZ|9.250378143E10|00614|      B2|
| 30.0|2016.0|   4.0| 101.0| 101.0|    ATL|20545.0|    1.0|     NJ|20578.0|  49.0|    2.0|  1.0|20160401|     TIA| null|      G|      O|   null|      M| 1967.0|09302016|     M|  null|     OS|9.247020943E10|00089|      B2|
| 31.0|2016.0|   4.0| 101.0| 101.0|    ATL|20545.0|    1.0|     NY|20611.0|  43.0|    2.0|  1.0|20160401|     TIA| null|      G|      O|   null|      M| 1973.0|09302016|     M|  null|     OS|9.247128923E10|00089|      B2|
| 33.0|2016.0|   4.0| 101.0| 101.0|    HOU|20545.0|    1.0|     TX|20554.0|  53.0|    2.0|  1.0|20160401|     TIA| null|      G|      O|   null|      M| 1963.0|09302016|     F|  null|     TK|9.250930163E10|00033|      B2|
| 34.0|2016.0|   4.0| 101.0| 101.0|    NYC|20545.0|    1.0|     CT|   null|  48.0|    2.0|  1.0|20160401|     TIA| null|      G|   null|   null|   null| 1968.0|09302016|     M|  null|     AZ|9.247042023E10|00602|      B2|
| 35.0|2016.0|   4.0| 101.0| 101.0|    NYC|20545.0|    1.0|     CT|   null|  74.0|    2.0|  1.0|20160401|     TIA| null|      T|   null|   null|   null| 1942.0|09302016|     F|  null|     TK|  6.69712185E8|    1|      B2|
+-----+------+------+------+------+-------+-------+-------+-------+-------+------+-------+-----+--------+--------+-----+-------+-------+-------+-------+-------+--------+------+------+-------+--------------+-----+--------+
only showing top 20 rows

In [24]:
# Performing cleaning tasks here
i94_table = df_i94.selectExpr(["i94yr as year",
                              "i94mon as month",
                              "i94cit as country_birth_id",
                              "i94res as country_residence_id",
                              "i94port as port_code",
                              "arrdate as arrival_date",
                              "i94mode as transport_mode",
                              "i94addr as state_code",
                              "depdate as departure_from_usa",
                              "i94bir as age",
                              "i94visa as visa_code",
                              "count",
                              "dtadfile",
                              "visapost",
                              "occup",
                              "entdepa",
                              "entdepd",
                              "entdepu",
                              "matflag",
                              "biryear as birth_year",
                              "dtaddto as allowed_to_stay_until",
                              "gender",
                              "insnum as ins_num",
                              "airline",
                              "admnum as admission_num",
                              "fltno as flight_num",
                              "visatype as visa_type"])

i94_table.printSchema()

root
 |-- year: double (nullable = true)
 |-- month: double (nullable = true)
 |-- country_birth_id: double (nullable = true)
 |-- country_residence_id: double (nullable = true)
 |-- port_code: string (nullable = true)
 |-- arrival_date: double (nullable = true)
 |-- transport_mode: double (nullable = true)
 |-- state_code: string (nullable = true)
 |-- departure_from_usa: double (nullable = true)
 |-- age: double (nullable = true)
 |-- visa_code: double (nullable = true)
 |-- count: double (nullable = true)
 |-- dtadfile: string (nullable = true)
 |-- visapost: string (nullable = true)
 |-- occup: string (nullable = true)
 |-- entdepa: string (nullable = true)
 |-- entdepd: string (nullable = true)
 |-- entdepu: string (nullable = true)
 |-- matflag: string (nullable = true)
 |-- birth_year: double (nullable = true)
 |-- allowed_to_stay_until: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- ins_num: string (nullable = true)
 |-- airline: string (nullable = true)
 |-- admission_num: double (nullable = true)
 |-- flight_num: string (nullable = true)
 |-- visa_type: string (nullable = true)

In [25]:
i94_table.filter(i94_table.transport_mode==3.0).limit(10).toPandas()

,year,month,country_birth_id,country_residence_id,port_code,arrival_date,transport_mode,state_code,departure_from_usa,age,...,entdepu,matflag,birth_year,allowed_to_stay_until,gender,ins_num,airline,admission_num,flight_num,visa_type
0,2016.0,4.0,101.0,101.0,DAL,20559.0,3.0,NY,20562.0,27.0,...,None,M,1989.0,10142016,F,None,None,9.362681e+10,LAND,B2
1,2016.0,4.0,574.0,101.0,DET,20555.0,3.0,MO,NaN,38.0,...,None,None,1978.0,03142018,F,None,None,9.068215e+10,01601,E2
2,2016.0,4.0,101.0,101.0,DET,20567.0,3.0,None,20568.0,31.0,...,None,M,1985.0,05192016,F,None,None,7.986382e+10,LAND,B2
3,2016.0,4.0,101.0,101.0,DET,20574.0,3.0,MI,20576.0,27.0,...,None,M,1989.0,06242016,M,None,None,8.331251e+10,LAND,B2
4,2016.0,4.0,101.0,101.0,DET,20567.0,3.0,None,20569.0,60.0,...,None,M,1956.0,06292016,F,None,None,8.396096e+10,LAND,B2
5,2016.0,4.0,101.0,101.0,DET,20567.0,3.0,None,20569.0,65.0,...,None,M,1951.0,06292016,M,None,None,8.396123e+10,LAND,B2
6,2016.0,4.0,101.0,101.0,DET,20570.0,3.0,None,20643.0,32.0,...,None,M,1984.0,06292016,F,None,None,8.409472e+10,LAND,B2
7,2016.0,4.0,101.0,101.0,HOU,20552.0,3.0,NY,20555.0,34.0,...,None,M,1982.0,10072016,M,None,None,7.195148e+08,LAND,B2
8,2016.0,4.0,101.0,101.0,LEW,20574.0,3.0,None,20576.0,50.0,...,None,M,1966.0,08262016,F,None,None,8.917981e+10,LAND,B2
9,2016.0,4.0,101.0,101.0,LEW,20574.0,3.0,NY,20578.0,30.0,...,None,M,1986.0,10292016,M,None,None,9.500240e+10,LAND,B2

### Step 3: Define the Data Model
#### 3.1 Conceptual Data Model
Map out the conceptual data model and explain why you chose that model

#### 3.2 Mapping Out Data Pipelines
List the steps necessary to pipeline the data into the chosen data model

### Step 4: Run Pipelines to Model the Data 
#### 4.1 Create the data model
Build the data pipelines to create the data model.

In [26]:
# Write code here

#### 4.2 Data Quality Checks
Explain the data quality checks you'll perform to ensure the pipeline ran as expected. These could include:
 * Integrity constraints on the relational database (e.g., unique key, data type, etc.)
 * Unit tests for the scripts to ensure they are doing the right thing
 * Source/Count checks to ensure completeness
 
Run Quality Checks

In [27]:
# Perform quality checks here

#### 4.3 Data dictionary 
Create a data dictionary for your data model. For each field, provide a brief description of what the data is and where it came from. You can include the data dictionary in the notebook or in a separate file.

#### Step 5: Complete Project Write Up
* Clearly state the rationale for the choice of tools and technologies for the project.
* Propose how often the data should be updated and why.
* Write a description of how you would approach the problem differently under the following scenarios:
 * The data was increased by 100x.
 * The data populates a dashboard that must be updated on a daily basis by 7am every day.
 * The database needed to be accessed by 100+ people.