# Project Title
### Data Engineering Capstone Project

#### Project Summary
--describe your project at a high level--

The project follows the follow steps:
* Step 1: Scope the Project and Gather Data
* Step 2: Explore and Assess the Data
* Step 3: Define the Data Model
* Step 4: Run ETL to Model the Data
* Step 5: Complete Project Write Up

In [1]:
# Do all imports and installs here
from pyspark.sql import SparkSession
import pandas as pd

In [2]:
from extractor import Extractor

### Step 1: Scope the Project and Gather Data

#### Scope 
Explain what you plan to do in the project in more detail. What data do you use? What is your end solution look like? What tools did you use? etc>

#### Describe and Gather Data 
Describe the data sets you're using. Where did it come from? What type of information is included?

In [3]:
filepaths = {
    'i94' : './data/18-83510-I94-Data-2016/i94_apr16_sub.sas7bdat',
    'airports' : './data/airport-codes_csv.csv',
    'states' : './data/states.csv',
    'transport_modes' : './data/transport_mode.csv',
    'visa' : './data/visa.csv',
    'cities' : './data/us-cities-demographics.csv'
}

In [4]:
spark = SparkSession \
        .builder \
        .config("spark.jars.packages","saurfang:spark-sas7bdat:2.0.0-s_2.11")\
        .enableHiveSupport()\
        .getOrCreate()

In [5]:
extractor = Extractor(spark, filepaths)

In [6]:
df_airports = extractor.get_airport_data()
df_cities = extractor.get_cities_data()
df_states = extractor.get_states_data()
df_trasnp_modes = extractor.get_transp_mode_data()
df_visas = extractor.get_visa_data()

In [7]:
df_airports.toPandas()

,ident,type,name,elevation_ft,continent,iso_country,iso_region,municipality,gps_code,iata_code,local_code,coordinates
0,00A,heliport,Total Rf Heliport,11,NA,US,US-PA,Bensalem,00A,None,00A,"-74.93360137939453, 40.07080078125"
1,00AA,small_airport,Aero B Ranch Airport,3435,NA,US,US-KS,Leoti,00AA,None,00AA,"-101.473911, 38.704022"
2,00AK,small_airport,Lowell Field,450,NA,US,US-AK,Anchor Point,00AK,None,00AK,"-151.695999146, 59.94919968"
3,00AL,small_airport,Epps Airpark,820,NA,US,US-AL,Harvest,00AL,None,00AL,"-86.77030181884766, 34.86479949951172"
4,00AR,closed,Newport Hospital & Clinic Heliport,237,NA,US,US-AR,Newport,None,None,None,"-91.254898, 35.6087"
5,00AS,small_airport,Fulton Airport,1100,NA,US,US-OK,Alex,00AS,None,00AS,"-97.8180194, 34.9428028"
6,00AZ,small_airport,Cordes Airport,3810,NA,US,US-AZ,Cordes,00AZ,None,00AZ,"-112.16500091552734, 34.305599212646484"
7,00CA,small_airport,Goldstone /Gts/ Airport,3038,NA,US,US-CA,Barstow,00CA,None,00CA,"-116.888000488, 35.350498199499995"
8,00CL,small_airport,Williams Ag Airport,87,NA,US,US-CA,Biggs,00CL,None,00CL,"-121.763427, 39.427188"
9,00CN,heliport,Kitchen Creek Helibase Heliport,3350,NA,US,US-CA,Pine Valley,00CN,None,00CN,"-116.4597417, 32.7273736"
10,00CO,closed,Cass Field,4830,NA,US,US-CO,Briggsdale,None,None,None,"-104.344002, 40.622202"
11,00FA,small_airport,Grass Patch Airport,53,NA,US,US-FL,Bushnell,00FA,None,00FA,"-82.21900177001953, 28.64550018310547"
12,00FD,heliport,Ringhaver Heliport,25,NA,US,US-FL,Riverview,00FD,None,00FD,"-82.34539794921875, 28.846599578857422"
13,00FL,small_airport,River Oak Airport,35,NA,US,US-FL,Okeechobee,00FL,None,00FL,"-80.96920013427734, 27.230899810791016"
14,00GA,small_airport,Lt World Airport,700,NA,US,US-GA,Lithonia,00GA,None,00GA,"-84.06829833984375, 33.76750183105469"
15,00GE,heliport,Caffrey Heliport,957,NA,US,US-GA,Hiram,00GE,None,00GE,"-84.73390197753906, 33.88420104980469"
16,00HI,heliport,Kaupulehu Heliport,43,NA,US,US-HI,Kailua/Kona,00HI,None,00HI,"-155.980233, 19.832715"
17,00ID,small_airport,Delta Shores Airport,2064,NA,US,US-ID,Clark Fork,00ID,None,00ID,"-116.21399688720703, 48.145301818847656"
18,00IG,small_airport,Goltl Airport,3359,NA,US,US-KS,McDonald,00IG,None,00IG,"-101.395994, 39.724028"
19,00II,heliport,Bailey Generation Station Heliport,600,NA,US,US-IN,Chesterton,00II,None,00II,"-87.122802734375, 41.644500732421875"
20,00IL,small_airport,Hammer Airport,840,NA,US,US-IL,Polo,00IL,None,00IL,"-89.5604019165039, 41.97840118408203"
21,00IN,heliport,St Mary Medical Center Heliport,634,NA,US,US-IN,Hobart,00IN,None,00IN,"-87.2605972290039, 41.51139831542969"
22,00IS,small_airport,Hayenga's Cant Find Farms Airport,820,NA,US,US-IL,Kings,00IS,None,00IS,"-89.1229019165039, 40.02560043334961"
23,00KS,small_airport,Hayden Farm Airport,1100,NA,US,US-KS,Gardner,00KS,None,00KS,"-94.93049621582031, 38.72779846191406"
24,00KY,small_airport,Robbins Roost Airport,1265,NA,US,US-KY,Stanford,00KY,None,00KY,"-84.61969757080078, 37.409400939941406"
25,00LA,heliport,Shell Chemical East Site Heliport,15,NA,US,US-LA,Gonzales,00LA,None,00LA,"-90.980833, 30.191944"
26,00LL,heliport,Ac & R Components Heliport,600,NA,US,US-IL,Chatham,00LL,None,00LL,"-89.70559692382812, 39.66529846191406"
27,00LS,small_airport,Lejeune Airport,12,NA,US,US-LA,Esterwood,00LS,None,00LS,"-92.42939758300781, 30.13629913330078"
28,00MD,small_airport,Slater Field,45,NA,US,US-MD,Federalsburg,00MD,None,00MD,"-75.75379943847656, 38.75709915161133"
29,00MI,heliport,Dow Chemical Heliport,588,NA,US,US-MI,Ludington,00MI,None,00MI,"-86.41670227050781, 43.94940185546875"
...,...,...,...,...,...,...,...,...,...,...,...,...
55045,ZYAS,medium_airport,Anshan Air Base,None,AS,CN,CN-21,Anshan,ZYAS,AOG,None,"122.853996, 41.105301"
55046,ZYCC,medium_airport,Longjia Airport,706,AS,CN,CN-22,Changchun,ZYCC,CGQ,None,"125.684997559, 43.9962005615"
55047,ZYCH,medium_airport,Changhai Airport,80,AS,CN,CN-21,Changhai,ZYCH,CNI,None,"122.666944444, 39.2666666667"
55048,ZYCY,medium_airport,Chaoyang Airport,568,AS,CN,CN-21,Chaoyang,ZYCY,CHG,None,"120.434998, 41.538101"
55049,ZYDU,medium_airport,Wudalianchi Dedu Airport,984,AS,CN,CN-23,Wudalianchi,ZYDU,DTU,None,"126.133, 48.445"
55050,ZYFX,small_airport,Fuxin Airport,548,AS,CN,CN-21,Fuxin,ZYFX,None,None,"121.718122, 42.069014"
55051,ZYFY,medium_airport,Dongji Aiport,None,AS,CN,CN-23,Fuyuan,ZYFY,FYJ,None,"134.366447, 48.199494"
55052,ZYHB,large_airport,Taiping Airport,457,AS,CN,CN-23,Harbin,ZYHB,HRB,None,"126.25, 45.6234016418457"
55053,ZYHE,medium_airport,Heihe Airport,8530,AS,CN,CN-23,Heihe,ZYHE,HEK,None,"127.308883667, 50.1716209371"
55054,ZYJL,small_airport,Jilin Airport,None,AS,CN,CN-22,Jilin,ZYJL,JIL,None,"126.396004, 44.002201"
55055,ZYJM,medium_airport,Jiamusi Airport,262,AS,CN,CN-23,Jiamusi,ZYJM,JMU,None,"130.464996338, 46.84339904789999"
55056,ZYJS,medium_airport,Jiansanjiang Airport,None,AS,CN,CN-23,Jiansanjiang,ZYJS,JSJ,None,"132.660278, 47.11"
55057,ZYJX,medium_airport,Jixi Xingkaihu Airport,760,AS,CN,CN-23,Jixi,ZYJX,JXA,None,"131.193, 45.293"
55058,ZYJZ,medium_airport,Jinzhou Airport,None,AS,CN,CN-21,Jinzhou,ZYJZ,JNZ,None,"121.06199645996094, 41.10139846801758"
55059,ZYLD,medium_airport,Lindu Airport,791,AS,CN,CN-23,Yichun,ZYLD,LDS,None,"129.019125, 47.7520555556"
55060,ZYLS,medium_airport,Yushu Batang Airport,12816,AS,CN,CN-63,Yushu,ZYLS,YUS,None,"97.0363888889, 32.836388888900004"
55061,ZYMD,medium_airport,Mudanjiang Hailang International Airport,883,AS,CN,CN-23,Mudanjiang,ZYMD,MDG,None,"129.569000244, 44.5241012573"
55062,ZYMH,medium_airport,Gu-Lian Airport,1836,AS,CN,CN-23,Mohe,ZYMH,OHE,None,"122.43, 52.912777777799995"
55063,ZYQQ,medium_airport,Qiqihar Sanjiazi Airport,477,AS,CN,CN-23,Qiqihar,ZYQQ,NDG,None,"123.91799926757812, 47.239601135253906"
55064,ZYSQ,medium_airport,Songyuan Chaganhu Airport,459,AS,CN,CN-22,Qian Gorlos Mongol Autonomous County,ZYSQ,YSQ,None,"124.550178, 44.938114"
55065,ZYTH,small_airport,Tahe Airport,1240,AS,CN,CN-23,Tahe,ZYTH,None,None,"124.720222222, 52.2244444444"
55066,ZYTL,large_airport,Zhoushuizi Airport,107,AS,CN,CN-21,Dalian,ZYTL,DLC,None,"121.53900146484375, 38.9656982421875"
55067,ZYTN,medium_airport,Tonghua Sanyuanpu Airport,1200,AS,CN,CN-22,Tonghua,ZYTN,TNH,None,"125.703333333, 42.2538888889"
55068,ZYTX,large_airport,Taoxian Airport,198,AS,CN,CN-21,Shenyang,ZYTX,SHE,None,"123.48300170898438, 41.639801025390625"
55069,ZYYJ,medium_airport,Yanji Chaoyangchuan Airport,624,AS,CN,CN-22,Yanji,ZYYJ,YNJ,None,"129.451004028, 42.8828010559"
55070,ZYYK,medium_airport,Yingkou Lanqi Airport,0,AS,CN,CN-21,Yingkou,ZYYK,YKH,None,"122.3586, 40.542524"
55071,ZYYY,medium_airport,Shenyang Dongta Airport,None,AS,CN,CN-21,Shenyang,ZYYY,None,None,"123.49600219726562, 41.784400939941406"
55072,ZZ-0001,heliport,Sealand Helipad,40,EU,GB,GB-ENG,Sealand,None,None,None,"1.4825, 51.894444"
55073,ZZ-0002,small_airport,Glorioso Islands Airstrip,11,AF,TF,TF-U-A,Grande Glorieuse,None,None,None,"47.296388888900005, -11.584277777799999"
55074,ZZZZ,small_airport,Satsuma IÅjima Airport,338,AS,JP,JP-46,Mishima-Mura,RJX7,None,None,"130.270556, 30.784722"

In [8]:
df_cities.toPandas()

,City,State,Median Age,Male Population,Female Population,Total Population,Number of Veterans,Foreign-born,Average Household Size,State Code,Race,Count
0,Silver Spring,Maryland,33.8,40601,41862,82463,1562,30908,2.6,MD,Hispanic or Latino,25924
1,Quincy,Massachusetts,41.0,44129,49500,93629,4147,32935,2.39,MA,White,58723
2,Hoover,Alabama,38.5,38040,46799,84839,4819,8229,2.58,AL,Asian,4759
3,Rancho Cucamonga,California,34.5,88127,87105,175232,5821,33878,3.18,CA,Black or African-American,24437
4,Newark,New Jersey,34.6,138040,143873,281913,5829,86253,2.73,NJ,White,76402
5,Peoria,Illinois,33.1,56229,62432,118661,6634,7517,2.4,IL,American Indian and Alaska Native,1343
6,Avondale,Arizona,29.1,38712,41971,80683,4815,8355,3.18,AZ,Black or African-American,11592
7,West Covina,California,39.8,51629,56860,108489,3800,37038,3.56,CA,Asian,32716
8,O'Fallon,Missouri,36.0,41762,43270,85032,5783,3269,2.77,MO,Hispanic or Latino,2583
9,High Point,North Carolina,35.5,51751,58077,109828,5204,16315,2.65,NC,Asian,11060
10,Folsom,California,40.9,41051,35317,76368,4187,13234,2.62,CA,Hispanic or Latino,5822
11,Folsom,California,40.9,41051,35317,76368,4187,13234,2.62,CA,American Indian and Alaska Native,998
12,Philadelphia,Pennsylvania,34.1,741270,826172,1567442,61995,205339,2.61,PA,Asian,122721
13,Wichita,Kansas,34.6,192354,197601,389955,23978,40270,2.56,KS,Hispanic or Latino,65162
14,Wichita,Kansas,34.6,192354,197601,389955,23978,40270,2.56,KS,American Indian and Alaska Native,8791
15,Fort Myers,Florida,37.3,36850,37165,74015,4312,15365,2.45,FL,White,50169
16,Pittsburgh,Pennsylvania,32.9,149690,154695,304385,17728,28187,2.13,PA,White,208863
17,Laredo,Texas,28.8,124305,131484,255789,4921,68427,3.66,TX,American Indian and Alaska Native,1253
18,Berkeley,California,32.5,60142,60829,120971,3736,25000,2.35,CA,Asian,27089
19,Santa Clara,California,35.2,63278,62938,126216,4426,52281,2.75,CA,White,55847
20,Allen,Pennsylvania,33.5,60626,59581,120207,5691,19652,2.67,PA,Black or African-American,22304
21,Hampton,Virginia,35.5,66214,70240,136454,19638,6204,2.48,VA,Black or African-American,70303
22,Bolingbrook,Illinois,33.7,36295,35801,72096,2951,15212,3.42,IL,American Indian and Alaska Native,323
23,Frederick,Maryland,36.1,33146,36336,69482,3870,14211,2.48,MD,White,49181
24,Sparks,Nevada,36.1,47780,48318,96098,7315,15690,2.63,NV,Hispanic or Latino,29159
25,Rancho Cordova,California,33.8,34844,36182,71026,4590,17020,2.86,CA,Asian,12653
26,Westminster,Colorado,37.8,54866,58251,113117,6512,11361,2.63,CO,Hispanic or Latino,23355
27,Lakewood,Colorado,37.7,76013,76576,152589,9988,14169,2.29,CO,Hispanic or Latino,33630
28,Flint,Michigan,35.3,48984,49313,98297,3757,2138,2.38,MI,White,44786
29,New Haven,Connecticut,29.9,63765,66545,130310,2567,25871,2.48,CT,American Indian and Alaska Native,2205
...,...,...,...,...,...,...,...,...,...,...,...,...
2861,Scranton,Pennsylvania,38.5,37975,39137,77112,5059,8069,2.39,PA,Asian,4722
2862,Aurora,Colorado,34.2,177899,180971,358870,25158,65816,2.82,CO,Asian,24673
2863,Redlands,California,36.2,33993,37035,71028,3445,8681,2.82,CA,Hispanic or Latino,19698
2864,Alhambra,California,41.0,42184,43388,85572,1673,44441,2.89,CA,Hispanic or Latino,31386
2865,Alhambra,California,41.0,42184,43388,85572,1673,44441,2.89,CA,Black or African-American,1905
2866,Rio Rancho,New Mexico,38.3,47251,46904,94155,8527,5200,2.86,NM,Black or African-American,3970
2867,Wyoming,Michigan,32.8,35967,39310,75277,3447,8612,2.65,MI,American Indian and Alaska Native,2444
2868,Reading,Pennsylvania,29.4,43668,44205,87873,2580,17043,2.95,PA,Asian,903
2869,Rialto,California,31.6,49902,53235,103137,2036,32741,3.83,CA,American Indian and Alaska Native,1065
2870,Tallahassee,Florida,26.2,89390,100504,189894,9575,16720,2.38,FL,Asian,10035
2871,Hemet,California,36.8,38622,45251,83873,5613,13330,2.97,CA,Asian,3697
2872,Aurora,Illinois,31.7,101964,101751,203715,4988,50980,3.3,IL,Black or African-American,23736
2873,Carmel,Indiana,39.9,42928,46101,89029,2723,9645,2.71,IN,White,77178
2874,Glendale,California,42.1,98181,102844,201025,4448,111510,2.69,CA,Hispanic or Latino,30807
2875,Des Moines,Iowa,34.5,103726,106591,210317,11780,23857,2.41,IA,White,168057
2876,College Station,Texas,22.9,54125,53774,107899,2471,16145,2.52,TX,White,84892
2877,Peoria,Arizona,36.9,80139,91103,171242,13019,14260,2.97,AZ,Asian,6631
2878,Charlotte,North Carolina,34.3,396646,430475,827121,36046,128897,2.52,NC,American Indian and Alaska Native,8746
2879,Lafayette,Indiana,33.5,34313,36857,71170,5045,5697,2.19,IN,Hispanic or Latino,9151
2880,Abilene,Texas,31.3,65212,60664,125876,9367,8129,2.64,TX,Black or African-American,14449
2881,Gulfport,Mississippi,35.1,33108,38764,71872,6646,3072,2.54,MS,White,42870
2882,Davis,California,26.3,33493,34163,67656,2176,13997,2.69,CA,American Indian and Alaska Native,779
2883,Los Angeles,California,35.0,1958998,2012898,3971896,85417,1485425,2.86,CA,Black or African-American,404868
2884,Mount Vernon,New York,38.5,31876,36745,68621,2064,23777,2.85,NY,Hispanic or Latino,9446
2885,Lynchburg,Virginia,28.7,38614,41198,79812,4322,4364,2.48,VA,White,53727
2886,Stockton,California,32.5,150976,154674,305650,12822,79583,3.16,CA,American Indian and Alaska Native,19834
2887,Southfield,Michigan,41.6,31369,41808,73177,4035,4011,2.27,MI,American Indian and Alaska Native,983
2888,Indianapolis,Indiana,34.1,410615,437808,848423,42186,72456,2.53,IN,White,553665
2889,Somerville,Massachusetts,31.0,41028,39306,80334,2103,22292,2.43,MA,American Indian and Alaska Native,374
2890,Coral Springs,Florida,37.2,63316,66186,129502,4724,38552,3.17,FL,White,90896

In [9]:
df_trasnp_modes.toPandas()

  transport_mode_code  transport_mode
0                   1           'Air'
1                   2           'Sea'
2                   3          'Land'
3                   9  'Not reported'

In [10]:
df_visas.toPandas()

  visa_code   visa_type
0         1  'Business'
1         2  'Pleasure'
2         3   'Student'

In [11]:
df_i94 = extractor.get_i94_data()
df_i94.printSchema()

root
 |-- cicid: double (nullable = true)
 |-- i94yr: double (nullable = true)
 |-- i94mon: double (nullable = true)
 |-- i94cit: double (nullable = true)
 |-- i94res: double (nullable = true)
 |-- i94port: string (nullable = true)
 |-- arrdate: double (nullable = true)
 |-- i94mode: double (nullable = true)
 |-- i94addr: string (nullable = true)
 |-- depdate: double (nullable = true)
 |-- i94bir: double (nullable = true)
 |-- i94visa: double (nullable = true)
 |-- count: double (nullable = true)
 |-- dtadfile: string (nullable = true)
 |-- visapost: string (nullable = true)
 |-- occup: string (nullable = true)
 |-- entdepa: string (nullable = true)
 |-- entdepd: string (nullable = true)
 |-- entdepu: string (nullable = true)
 |-- matflag: string (nullable = true)
 |-- biryear: double (nullable = true)
 |-- dtaddto: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- insnum: string (nullable = true)
 |-- airline: string (nullable = true)
 |-- admnum: double (nullable = true)
 |-- fltno: string (nullable = true)
 |-- visatype: string (nullable = true)

In [42]:
df_cities.toPandas()['State Code'].unique()

array(['MD', 'MA', 'AL', 'CA', 'NJ', 'IL', 'AZ', 'MO', 'NC', 'PA', 'KS',
       'FL', 'TX', 'VA', 'NV', 'CO', 'MI', 'CT', 'MN', 'UT', 'AR', 'TN',
       'OK', 'WA', 'NY', 'GA', 'NE', 'KY', 'SC', 'LA', 'NM', 'IA', 'RI',
       'PR', 'DC', 'WI', 'OR', 'NH', 'ND', 'DE', 'OH', 'ID', 'IN', 'AK',
       'MS', 'HI', 'SD', 'ME', 'MT'], dtype=object)

In [9]:
#write to parquet
df_spark.write.parquet("sas_data")
df_spark=spark.read.parquet("sas_data")

NameError: name 'df_spark' is not defined

### Step 2: Explore and Assess the Data
#### Explore the Data 
Identify data quality issues, like missing values, duplicate data, etc.

#### Cleaning Steps
Document steps necessary to clean the data

In [12]:
df_i94.select('i94bir').toPandas().describe()

             i94bir
count  3.095511e+06
mean   4.176761e+01
std    1.742026e+01
min   -3.000000e+00
25%    3.000000e+01
50%    4.100000e+01
75%    5.400000e+01
max    1.140000e+02

In [11]:
for col in df_i94.columns:
    print("\n",col)
    print(df_i94.select(col).distinct().show(100))

 cicid
+-------+
|  cicid|
+-------+
|  299.0|
|  305.0|
|  496.0|
|  558.0|
|  596.0|
|  934.0|
| 1051.0|
| 1761.0|
| 2734.0|
| 2862.0|
| 3597.0|
| 3901.0|
| 3980.0|
| 4066.0|
| 4142.0|
| 5360.0|
| 5776.0|
| 5858.0|
| 5983.0|
| 6067.0|
| 6433.0|
| 6454.0|
| 6653.0|
| 6765.0|
| 7115.0|
| 7171.0|
| 7313.0|
| 7487.0|
| 7554.0|
| 7782.0|
| 8649.0|
| 9753.0|
| 9923.0|
|10024.0|
|10129.0|
|10338.0|
|10658.0|
|10831.0|
|10924.0|
|10930.0|
|11112.0|
|11757.0|
|11766.0|
|11772.0|
|11924.0|
|11935.0|
|12172.0|
|12275.0|
|12313.0|
|12467.0|
|12493.0|
|12671.0|
|12737.0|
|13094.0|
|13533.0|
|13607.0|
|13956.0|
|14024.0|
|14285.0|
|14452.0|
|14473.0|
|14768.0|
|15776.0|
|16596.0|
|16629.0|
|16822.0|
|16916.0|
|17072.0|
|17267.0|
|17884.0|
|18114.0|
|18436.0|
|19872.0|
|19878.0|
|20343.0|
|20467.0|
|20503.0|
|20511.0|
|20673.0|
|20689.0|
|20893.0|
|20948.0|
|21309.0|
|21356.0|
|21484.0|
|21606.0|
|21791.0|
|21825.0|
|21911.0|
|21933.0|
|22274.0|
|22331.0|
|22797.0|
|23527.0|
|23535.0|
|23678.0|
|23796.0|
|24533.0|
|24594.0|
|24801.0|
+-------+
only showing top 100 rows

None

 i94yr
+------+
| i94yr|
+------+
|2016.0|
+------+

None

 i94mon
+------+
|i94mon|
+------+
|   4.0|
+------+

None

 i94cit
+------+
|i94cit|
+------+
| 692.0|
| 299.0|
| 769.0|
| 147.0|
| 576.0|
| 735.0|
| 311.0|
| 206.0|
| 524.0|
| 389.0|
| 390.0|
| 249.0|
| 329.0|
| 112.0|
| 154.0|
| 521.0|
| 124.0|
| 438.0|
| 348.0|
| 410.0|
| 253.0|
| 317.0|
| 128.0|
| 201.0|
| 108.0|
| 387.0|
| 180.0|
| 763.0|
| 255.0|
| 369.0|
| 133.0|
| 509.0|
| 733.0|
| 155.0|
| 214.0|
| 301.0|
| 584.0|
| 350.0|
| 687.0|
| 101.0|
| 579.0|
| 217.0|
| 116.0|
| 167.0|
| 342.0|
| 745.0|
| 107.0|
| 268.0|
| 413.0|
| 602.0|
| 508.0|
| 728.0|
| 412.0|
| 236.0|
| 388.0|
| 465.0|
| 514.0|
| 689.0|
| 151.0|
| 721.0|
| 258.0|
| 577.0|
| 275.0|
| 529.0|
| 578.0|
| 218.0|
| 324.0|
| 120.0|
| 440.0|
| 513.0|
| 393.0|
| 251.0|
| 159.0|
| 765.0|
| 373.0|
| 688.0|
| 339.0|
| 518.0|
| 272.0|
| 274.0|
| 574.0|
| 207.0|
| 267.0|
| 104.0|
| 603.0|
| 250.0|
| 266.0|
| 114.0|
| 121.0|
| 166.0|
| 734.0|
| 345.0|
| 344.0|
| 220.0|
| 582.0|
| 414.0|
| 696.0|
| 464.0|
| 581.0|
| 204.0|
+------+
only showing top 100 rows

None

 i94res
+------+
|i94res|
+------+
| 692.0|
| 299.0|
| 576.0|
| 735.0|
| 206.0|
| 524.0|
| 389.0|
| 390.0|
| 249.0|
| 329.0|
| 112.0|
| 154.0|
| 521.0|
| 124.0|
| 438.0|
| 348.0|
| 410.0|
| 253.0|
| 317.0|
| 128.0|
| 201.0|
| 353.0|
| 108.0|
| 387.0|
| 255.0|
| 271.0|
| 369.0|
| 509.0|
| 469.0|
| 214.0|
| 155.0|
| 584.0|
| 301.0|
| 687.0|
| 350.0|
| 101.0|
| 579.0|
| 321.0|
| 217.0|
| 116.0|
| 745.0|
| 167.0|
| 342.0|
| 107.0|
| 268.0|
| 413.0|
| 602.0|
| 508.0|
| 412.0|
| 514.0|
| 236.0|
| 388.0|
| 689.0|
| 721.0|
| 151.0|
| 577.0|
| 529.0|
| 275.0|
| 258.0|
| 346.0|
| 218.0|
| 324.0|
| 120.0|
| 161.0|
| 440.0|
| 513.0|
| 393.0|
| 139.0|
| 251.0|
| 511.0|
| 159.0|
| 688.0|
| 373.0|
| 409.0|
| 339.0|
| 518.0|
| 272.0|
| 274.0|
| 207.0|
| 104.0|
| 603.0|
| 250.0|
| 266.0|
| 270.0|
| 121.0|
| 114.0|
| 166.0|
| 345.0|
| 344.0|
| 582.0|
| 220.0|
| 414.0|
| 216.0|
| 149.0|
| 696.0|
| 581.0|
| 464.0|
| 340.0|
| 204.0|
| 245.0|
+------+
only showing top 100 rows

None

 i94port
+-------+
|i94port|
+-------+
|    FMY|
|    BGM|
|    HEL|
|    DNS|
|    MOR|
|    FOK|
|    HVR|
|    SNA|
|    PTK|
|    SPM|
|    CLG|
|    OPF|
|    DLB|
|    ABS|
|    NAS|
|    MYR|
|    PVD|
|    OAK|
|    FAR|
|    OTT|
|    PBB|
|    WAR|
|    CRY|
|    NRN|
|    DET|
|    FRT|
|    NOO|
|    REN|
|    BEE|
|    AGN|
|    FAL|
|    MTH|
|    AGA|
|    NRT|
|    OTM|
|    ROS|
|    BWM|
|    LEX|
|    NSV|
|    RIF|
|    SFR|
|    ADW|
|    VCV|
|    COB|
|    RAY|
|    JFA|
|    BHX|
|    GPM|
|    SAV|
|    LLB|
|    HAR|
|    HAM|
|    EGP|
|    HAL|
|    LYN|
|    SHA|
|    ANA|
|    ROM|
|    WIL|
|    BED|
|    MWH|
|    PEM|
|    YIP|
|    NOG|
|    WBE|
|    MOB|
|    CHM|
|    SCH|
|    RYY|
|    LVG|
|    LIH|
|    TUC|
|    HNS|
|    SSM|
|    CNA|
|    BUF|
|    TRO|
|    MOO|
|    BAL|
|    ERC|
|    HPN|
|    PTL|
|    AUS|
|    SGR|
|    PHR|
|    HEF|
|    ATW|
|    FTF|
|    CRQ|
|    YHC|
|    PAR|
|    LWT|
|    SRQ|
|    RNO|
|    X44|
|    WLL|
|    FRB|
|    FTC|
|    NOL|
|    LNB|
+-------+
only showing top 100 rows

None

 arrdate
+-------+
|arrdate|
+-------+
|20550.0|
|20556.0|
|20553.0|
|20551.0|
|20565.0|
|20563.0|
|20546.0|
|20547.0|
|20554.0|
|20564.0|
|20545.0|
|20560.0|
|20573.0|
|20559.0|
|20574.0|
|20567.0|
|20555.0|
|20570.0|
|20569.0|
|20549.0|
|20558.0|
|20571.0|
|20557.0|
|20562.0|
|20568.0|
|20561.0|
|20552.0|
|20566.0|
|20548.0|
|20572.0|
+-------+

None

 i94mode
+-------+
|i94mode|
+-------+
|   null|
|    1.0|
|    3.0|
|    2.0|
|    9.0|
+-------+

None

 i94addr
+-------+
|i94addr|
+-------+
|     .N|
|     RG|
|     YH|
|     RF|
|     FT|
|     CI|
|     TC|
|     SC|
|     AZ|
|     FI|
|     IC|
|     PU|
|     UA|
|     EA|
|     NS|
|     KI|
|     RO|
|     PI|
|     SL|
|     LA|
|     YN|
|     NL|
|     MN|
|     BS|
|     FC|
|     BW|
|     11|
|     NK|
|     OI|
|     RE|
|     PS|
|     PL|
|     AM|
|     AA|
|     MK|
|     NJ|
|     DR|
|     73|
|     RA|
|     WC|
|     MX|
|     HW|
|      3|
|     30|
|     JF|
|      F|
|     VL|
|     DC|
|     QL|
|     TV|
|     GL|
|     EE|
|     EX|
|     PD|
|     VG|
|     ZN|
|     CN|
|     4B|
|     S6|
|     OR|
|     FG|
|     JC|
|     UR|
|     RY|
|     UM|
|     AT|
|     TI|
|     85|
|     NW|
|     OL|
|     SW|
|     UL|
|     52|
|     HH|
|     AV|
|     NA|
|     GO|
|      0|
|     BU|
|     LF|
|     HY|
|     IQ|
|     RU|
|     KF|
|     71|
|     EV|
|     SJ|
|     EQ|
|     99|
|     XN|
|     CG|
|     NT|
|     LI|
|     HR|
|     SV|
|   null|
|     VA|
|     NP|
|     WE|
|     BX|
+-------+
only showing top 100 rows

None

 depdate
+-------+
|depdate|
+-------+
|20593.0|
|20689.0|
|20673.0|
|20467.0|
|20652.0|
|20196.0|
|20705.0|
|20621.0|
|20550.0|
|20682.0|
|20203.0|
|20592.0|
|20614.0|
|20556.0|
|20683.0|
|20518.0|
|20553.0|
|20622.0|
|20527.0|
|20699.0|
|20620.0|
|20671.0|
|20709.0|
|20666.0|
|20584.0|
|20656.0|
|20594.0|
|20629.0|
|20618.0|
|20605.0|
|20631.0|
|20672.0|
|20551.0|
|20707.0|
|20624.0|
|20669.0|
|20565.0|
|20639.0|
|20651.0|
|20641.0|
|20714.0|
|20653.0|
|20523.0|
|20544.0|
|20563.0|
|20644.0|
|20466.0|
|20463.0|
|20696.0|
|   null|
|20636.0|
|20688.0|
|20677.0|
|20694.0|
|20591.0|
|20693.0|
|20546.0|
|20662.0|
|20541.0|
|20524.0|
|20626.0|
|20530.0|
|20547.0|
|20579.0|
|20590.0|
|20596.0|
|20554.0|
|20517.0|
|20181.0|
|20687.0|
|20609.0|
|20617.0|
|20713.0|
|20430.0|
|20603.0|
|19860.0|
|20611.0|
|20659.0|
|20564.0|
|20661.0|
|20533.0|
|20595.0|
|20667.0|
|20587.0|
|20615.0|
|19095.0|
|20680.0|
|20545.0|
|20608.0|
|20468.0|
|20640.0|
|20528.0|
|20684.0|
|20443.0|
|20685.0|
|20665.0|
|20520.0|
|20678.0|
|20635.0|
|20628.0|
+-------+
only showing top 100 rows

None

 i94bir
+------+
|i94bir|
+------+
|  70.0|
|  67.0|
|   8.0|
|   0.0|
|  69.0|
|   7.0|
| 108.0|
|  88.0|
|  49.0|
| 101.0|
|  98.0|
|  29.0|
| 107.0|
|  64.0|
|  75.0|
|  47.0|
|  42.0|
|  44.0|
|  62.0|
|  35.0|
|  96.0|
|  null|
|  18.0|
|  80.0|
|  86.0|
|  -3.0|
|  39.0|
|   1.0|
|  94.0|
| 114.0|
|  37.0|
|  34.0|
|  25.0|
|  36.0|
|  41.0|
|   4.0|
|  85.0|
|  23.0|
|  77.0|
|  56.0|
|  50.0|
|  78.0|
|  79.0|
|  45.0|
|  83.0|
|  71.0|
|  93.0|
|  31.0|
|  11.0|
| 103.0|
|  58.0|
|  51.0|
|  21.0|
|  72.0|
|  14.0|
| 109.0|
|  63.0|
| 111.0|
|  48.0|
|  22.0|
|  82.0|
|  74.0|
|  60.0|
|  66.0|
|  68.0|
|  53.0|
|   3.0|
|  19.0|
|  61.0|
|  59.0|
|  81.0|
|  46.0|
|  28.0|
|  57.0|
|   2.0|
|  87.0|
|  17.0|
|  38.0|
|  27.0|
|  10.0|
|  73.0|
|  40.0|
|  30.0|
|  13.0|
|  99.0|
|  95.0|
| 100.0|
| 102.0|
|  33.0|
|  84.0|
|  92.0|
|   6.0|
|  20.0|
|  52.0|
|  32.0|
|  24.0|
|   5.0|
|  15.0|
|  97.0|
| 105.0|
+------+
only showing top 100 rows

None

 i94visa
+-------+
|i94visa|
+-------+
|    1.0|
|    3.0|
|    2.0|
+-------+

None

 count
+-----+
|count|
+-----+
|  1.0|
+-----+

None

 dtadfile
+--------+
|dtadfile|
+--------+
|20160429|
|20160615|
|20160825|
|20160604|
|20160403|
|20160611|
|20160623|
|20160427|
|20160420|
|20160423|
|20160702|
|20160529|
|20160422|
|20160405|
|20160609|
|20160525|
|20160709|
|20160617|
|20160628|
|20160830|
|20160504|
|20160619|
|20160507|
|20160901|
|    null|
|20160624|
|20160823|
|20160730|
|20160408|
|20160516|
|20160528|
|20160410|
|20160421|
|20160517|
|20160425|
|20160810|
|20160813|
|20160506|
|20160802|
|20160603|
|20160906|
|20160817|
|20160518|
|20160411|
|20160512|
|20160409|
|20160524|
|20160831|
|20130811|
|20160406|
|20160415|
|20160520|
|20160618|
|20160505|
|20160914|
|20160419|
|20160417|
|20160824|
|20160404|
|20160917|
|20160601|
|20160428|
|20160509|
|20160801|
|20160829|
|20160606|
|20160521|
|20160501|
|20160407|
|20160630|
|20160902|
|20160414|
|20160426|
|20160720|
|20160430|
|20160511|
|20160513|
|20160613|
|20160503|
|20160402|
|20160610|
|20160416|
|20160816|
|20160916|
|20160622|
|20160826|
|20160714|
|20160424|
|20160620|
|20160523|
|20160531|
|20160626|
|20160815|
|20160915|
|20160514|
|20160502|
|20160909|
|20160913|
|20160706|
|20160918|
+--------+
only showing top 100 rows

None

 visapost

+--------+
|visapost|
+--------+
|     CRS|
|     KGL|
|     AKD|
|     BGM|
|     TRK|
|     MOR|
|     MDL|
|     KAT|
|     FRN|
|     CJT|
|     MBO|
|     OSK|
|     LND|
|     SNA|
|     MXT|
|     CLG|
|     BRA|
|     SPM|
|     ZZZ|
|     GRB|
|     NGL|
|     CAR|
|     MDD|
|     TKY|
|     TEG|
|     KRK|
|     SPL|
|     ABS|
|     NAS|
|     POZ|
|     MDR|
|     ALG|
|     FTN|
|     IST|
|     BRN|
|     CPC|
|     MDN|
|     WAR|
|     KNG|
|     OTT|
|     CRY|
|     JOH|
|     NUK|
|     QUE|
|     OUA|
|     ESC|
|     RCF|
|     DET|
|     BDT|
|     SNS|
|     STA|
|     OSL|
|     ODP|
|     VIE|
|     CPN|
|     HML|
|     GEN|
|     TEL|
|     CPT|
|     BEE|
|     TAC|
|     PDE|
|     BRT|
|     AGA|
|     BUE|
|     LSB|
|     BNK|
|     OTM|
|     SEO|
|     LXM|
|     LAG|
|     BRL|
|     RNG|
|     FLO|
|     RKJ|
|     SNY|
|     GTM|
|     IOT|
|     AMB|
|     SFR|
|     TIA|
|     ABD|
|     KNV|
|     RAY|
|     VCV|
|     COB|
|     JER|
|     JDD|
|     CLA|
|     HER|
|     ZGB|
|     PEK|
|     TRT|
|     EGP|
|     GUA|
|     BRV|
|     DHR|
|     ROM|
|     SPN|
|     SHA|
+--------+
only showing top 100 rows

None

 occup
+-----+
|occup|
+-----+
|  PHA|
|  ENT|
|  REL|
|  ACH|
|  101|
|  EMM|
|  ULS|
|  GEN|
|  DVM|
|  MTH|
|  SVC|
|  ECH|
|  EXA|
|  ENV|
|  ENP|
|  PRF|
|  VOC|
| null|
|  AST|
|  TCH|
|  MSC|
|  HFM|
|  ACN|
|  ORS|
|  300|
|  HSW|
|  TCC|
|  ECO|
|  PRD|
|  ATH|
|  LAC|
|  PHR|
|  NAW|
|  999|
|  ADM|
|  EAS|
|  PPS|
|  UNP|
|  PRS|
|  ECV|
|  HEH|
|  SLS|
|  MCH|
|  RPT|
|  CPA|
|  AGR|
|  L1M|
|  TTP|
|  LLJ|
|  WTR|
|  RET|
|  POD|
|  ELT|
|  NOT|
|  MGR|
|  EAG|
|  UNK|
|  FLG|
|  TIE|
|  DDS|
|  SCL|
|  PHS|
|  TIP|
|  GLS|
|  CEO|
|  STU|
|  CLN|
|  RHC|
|  OTH|
|  MVC|
|  MKT|
|  049|
|  CNS|
|  EDR|
|  992|
|  NRR|
|  DOC|
|  REI|
|  EMC|
|  CAN|
|  RAS|
|  PSV|
|  REB|
|  RBC|
|  ELE|
|  HMK|
|  SCS|
|  TCN|
|  TEC|
|  PHY|
|  TTE|
|  SCP|
|  BIL|
|  PSY|
|  EIN|
|  FBP|
|  855|
|  ASP|
|  HSV|
|  ENO|
+-----+
only showing top 100 rows

None

 entdepa
+-------+
|entdepa|
+-------+
|      K|
|      F|
|   null|
|      T|
|      B|
|      M|
|      U|
|      O|
|      Z|
|      A|
|      N|
|      G|
|      P|
|      H|
+-------+

None

 entdepd
+-------+
|entdepd|
+-------+
|      K|
|      Q|
|   null|
|      M|
|      L|
|      V|
|      O|
|      D|
|      J|
|      N|
|      W|
|      R|
|      I|
+-------+

None

 entdepu
+-------+
|entdepu|
+-------+
|   null|
|      Y|
|      U|
+-------+

None

 matflag
+-------+
|matflag|
+-------+
|   null|
|      M|
+-------+

None

 biryear
+-------+
|biryear|
+-------+
| 1988.0|
| 1951.0|
| 1976.0|
| 1940.0|
| 1928.0|
| 1979.0|
| 1953.0|
| 1913.0|
| 1987.0|
| 1909.0|
| 1959.0|
| 1934.0|
| 1978.0|
| 1968.0|
| 2010.0|
|   null|
| 1936.0|
| 1902.0|
| 1967.0|
| 1964.0|
| 1916.0|
| 1993.0|
| 1906.0|
| 2001.0|
| 1954.0|
| 1965.0|
| 1984.0|
| 1973.0|
| 1980.0|
| 1966.0|
| 1997.0|
| 1907.0|
| 1992.0|
| 1990.0|
| 1995.0|
| 2009.0|
| 1938.0|
| 1945.0|
| 1949.0|
| 1927.0|
| 2007.0|
| 1914.0|
| 1932.0|
| 1960.0|
| 1950.0|
| 1937.0|
| 1922.0|
| 1930.0|
| 1996.0|
| 1943.0|
| 1963.0|
| 1933.0|
| 1929.0|
| 1969.0|
| 1918.0|
| 1986.0|
| 1939.0|
| 1998.0|
| 1956.0|
| 1917.0|
| 1985.0|
| 1923.0|
| 1944.0|
| 2019.0|
| 1957.0|
| 1925.0|
| 1982.0|
| 1948.0|
| 2000.0|
| 1994.0|
| 1970.0|
| 1952.0|
| 2008.0|
| 1981.0|
| 1999.0|
| 1921.0|
| 1908.0|
| 1975.0|
| 2011.0|
| 1931.0|
| 1989.0|
| 2002.0|
| 1926.0|
| 1958.0|
| 1962.0|
| 1920.0|
| 1942.0|
| 1911.0|
| 2006.0|
| 1919.0|
| 1961.0|
| 2004.0|
| 1941.0|
| 2013.0|
| 1955.0|
| 1947.0|
| 1905.0|
| 2012.0|
| 1915.0|
| 1972.0|
+-------+
only showing top 100 rows

None

 dtaddto
+--------+
| dtaddto|
+--------+
|09282016|
|02282017|
|10202017|
|11292017|
|11162016|
|01102017|
|06152016|
|03152017|
|03262017|
|11142016|
|01192018|
|04102016|
|07032016|
|07202019|
|06082019|
|05232016|
|08042016|
|03292017|
|04082018|
|08042017|
|08262016|
|08102016|
|08052017|
|02182018|
|01032018|
|10172017|
|11022016|
|09062017|
|05042016|
|07122016|
|05092017|
|10182016|
|04232017|
|09262016|
|03192017|
|10102017|
|04152018|
|01092017|
|03092018|
|11052017|
|02052018|
|06192017|
|04122018|
|07142019|
|09062016|
|05072016|
|10242016|
|03072017|
|03012018|
|10312016|
|11182017|
|09092017|
|04192018|
|05302019|
|01302018|
|04222017|
|02152017|
|08192016|
|04162016|
|03162018|
|02112017|
|05122016|
|12232017|
|10032017|
|09202016|
|01172018|
|01022017|
|08292017|
|04282019|
|07172016|
|11282016|
|11042017|
|04032019|
|06272017|
|09182017|
|02072017|
|09232016|
|08182016|
|02152018|
|01142018|
|04202017|
|05012017|
|07302017|
|02162018|
|07102016|
|03282018|
|09282017|
|09242016|
|07192016|
|02062018|
|02192018|
|02132017|
|07062017|
|12022017|
|01062018|
|11012016|
|12262016|
|02082017|
|12162016|
|06302017|
+--------+
only showing top 100 rows

None

 gender
+------+
|gender|
+------+
|     F|
|  null|
|     M|
|     U|
|     X|
+------+

None

 insnum
+------+
|insnum|
+------+
|  5325|
|  3414|
|  7252|
|  4032|
|  3959|
| 39645|
| 39590|
|   691|
| 39458|
|  4821|
|  5023|
|  3517|
|  5149|
|  3441|
|  5067|
|  3281|
|  3826|
| 38900|
|  3650|
|  1669|
|  3368|
|  2393|
|  4894|
|  4838|
|  1808|
|  1746|
|  3526|
|  5181|
|  5044|
|  7208|
|  4850|
|  3949|
|  2696|
|368006|
|  2700|
|393306|
|  2530|
|  5057|
|  3652|
|  4665|
|  5234|
|  2930|
|  1903|
|  2550|
|  3993|
|  6758|
|  5048|
|  3895|
|   475|
|  3902|
|  3898|
| 17274|
|  5543|
|  4736|
|  4719|
|  5071|
|  7829|
|  4672|
|  5434|
|  2495|
|  3875|
| 36956|
| 39821|
|  8691|
|  4690|
|  4782|
|  4818|
|  7353|
|  1104|
|  3656|
|  5104|
|  3250|
|  4685|
|  2392|
|  4333|
|  3891|
|  3641|
|  2964|
|  4315|
|  3365|
|  4789|
|  2144|
|  1435|
|  5306|
|  3953|
|  4856|
|  3661|
|  2953|
| 39368|
|  7980|
|   383|
|  3454|
|  5170|
|  8682|
|  5412|
|  5179|
|  5096|
|  3983|
|  6952|
|  3863|
+------+
only showing top 100 rows

None

 airline
+-------+
|airline|
+-------+
|     LT|
|     MM|
|     DZ|
|     CI|
|    447|
|    YFA|
|     TC|
|     AZ|
|     FI|
|    R0E|
|    B01|
|    78B|
|     UA|
|     EA|
|     Q7|
|     VP|
|    FYG|
|    CHP|
|    743|
|     3M|
|     15|
|     KI|
|    635|
|     LA|
|     D5|
|     SB|
|     BW|
|     FC|
|     TB|
|    YNT|
|     BS|
|     PZ|
|     NK|
|    009|
|    P2P|
|     OI|
|     4O|
|     XL|
|    DPJ|
|    D0S|
|    XLA|
|    351|
|     AM|
|     PS|
|    HPJ|
|     PL|
|     AA|
|    0BA|
|    TOS|
|    0FR|
|     AY|
|    10A|
|    468|
|     NJ|
|     DR|
|     K8|
|    512|
|    459|
|     MX|
|    348|
|     YI|
|    0L7|
|     E9|
|      3|
|     IB|
|    PHM|
|    K0W|
|     ZZ|
|    874|
|    VIV|
|    789|
|    365|
|    524|
|    0AF|
|    DJT|
|    T4A|
|    V8S|
|     PD|
|     YF|
|    B0E|
|     LM|
|     M7|
|    692|
|     7Z|
|    203|
|     OR|
|    813|
|    843|
|    U9Y|
|     7A|
|    663|
|     AT|
|    RJD|
|    GUY|
|     SW|
|    742|
|     52|
|     UL|
|     AV|
|     HY|
+-------+
only showing top 100 rows

None

 admnum
+---------------+
|         admnum|
+---------------+
|5.5412292033E10|
|5.5457659733E10|
|5.5427268533E10|
|5.5454626433E10|
|5.5415501233E10|
|5.5419999333E10|
|5.5432153433E10|
|5.5420421033E10|
|5.5463666633E10|
|5.5437022833E10|
| 9.249575503E10|
|5.5438157633E10|
| 9.246162853E10|
| 9.248399983E10|
|5.5438886333E10|
|5.5415379333E10|
|5.5415756033E10|
|5.5463016733E10|
|5.5463931533E10|
|5.5447111633E10|
|5.5423014233E10|
|5.5411305733E10|
|5.5463386033E10|
|5.5448053033E10|
|5.5448218033E10|
|5.5453838033E10|
|5.5417068833E10|
|5.5413481933E10|
|5.5449204333E10|
|5.5440123933E10|
|5.5435080333E10|
|5.5464022233E10|
|5.5463655633E10|
|5.5444968433E10|
|5.5416047633E10|
|5.5463305433E10|
|5.5412001433E10|
|5.5443997733E10|
|5.5448224433E10|
|5.5425286733E10|
|5.5445124233E10|
|5.5433585233E10|
|5.5441977333E10|
|   6.67280285E8|
|5.5450510633E10|
|5.5452265033E10|
|5.5435606533E10|
|5.5442526433E10|
|5.5440746233E10|
|5.5454682333E10|
|5.5429540033E10|
|5.5429010133E10|
|5.5406077033E10|
| 9.246393023E10|
|5.5445021633E10|
|5.5461932233E10|
|5.5436895333E10|
|5.5457298533E10|
|5.5456591833E10|
|5.5409611733E10|
|5.5449920233E10|
|5.5406569233E10|
|5.5405893733E10|
|5.5405356533E10|
|5.5405748933E10|
|5.5449557233E10|
|5.5450237433E10|
| 9.243984943E10|
|5.5449300633E10|
|5.5441834333E10|
|5.5442696033E10|
|5.5407857133E10|
| 9.248564703E10|
|5.5448675433E10|
|5.5406842433E10|
|5.5406648033E10|
|5.5415255633E10|
|5.5458189533E10|
|5.5454362433E10|
|5.5431026933E10|
| 9.138550863E10|
|5.5461691133E10|
|5.5424194033E10|
|5.5459313333E10|
|   6.66678085E8|
|5.5411957433E10|
| 9.244843123E10|
|5.5450067933E10|
|5.5438294133E10|
|5.5422527533E10|
|5.5417835033E10|
|5.5437427033E10|
|5.5448902833E10|
|   6.66764185E8|
|5.5456341533E10|
|5.5418176033E10|
|5.5433902433E10|
|5.5440417133E10|
|5.5417438133E10|
|5.5429594033E10|
+---------------+
only showing top 100 rows

None

 fltno

+-----+
|fltno|
+-----+
|00456|
| 1159|
|00530|
| 1512|
|  296|
| 3606|
|00556|
|0059C|
| 2294|
|0990C|
|N800P|
|10096|
|  691|
|04319|
|XAGPR|
|00332|
| 4821|
|B8095|
|N415S|
|02090|
|1857C|
|GCEYL|
|XASTS|
|SEDJL|
|09120|
|0988C|
| 2069|
|VPBGM|
| 4032|
|N66EP|
|02070|
|03904|
|02053|
|03788|
|  125|
|90439|
|01692|
| 1394|
|09560|
|  944|
|07638|
|05647|
|2964C|
|02643|
|  853|
|YV196|
|94342|
|0126A|
|00709|
|08383|
|05831|
| 5657|
|02018|
|C6SEA|
|0482C|
|02573|
| 8092|
|N3364|
|XACPR|
| 1372|
|PTPCH|
| 1669|
|07856|
|02911|
|PRAJP|
|N3161|
|N131B|
|06083|
|08619|
|04880|
|00100|
|01631|
|00958|
|00960|
|00564|
|  870|
|07544|
|00192|
|08315|
|  919|
|  926|
| 7248|
|05966|
|08861|
| 4850|
|01264|
| 3949|
| 1870|
|0088C|
|06732|
|N602J|
|N172E|
| 646C|
|N405M|
|N773S|
|XAFLY|
|87043|
|2682C|
|C6AUD|
| 3526|
+-----+
only showing top 100 rows

None

 visatype
+--------+
|visatype|
+--------+
|      F2|
|     GMB|
|      B2|
|      F1|
|     CPL|
|      I1|
|      WB|
|      M1|
|      B1|
|      WT|
|      M2|
|      CP|
|     GMT|
|      E1|
|       I|
|      E2|
|     SBP|
+--------+

None

In [12]:
# Performing cleaning tasks here
i94_table = df_i94.selectExpr(["i94yr as year",
                              "i94mon as month",
                              "i94cit as country_birth_id",
                              "i94res as country_residence_id",
                              "i94port as port_code",
                              "arrdate as arrival_date",
                              "i94mode as transport_mode",
                              "i94addr as state_code",
                              "depdate as departure_from_usa",
                              "i94bir as age",
                              "i94visa as visa_code",
                              "count",
                              "dtadfile",
                              "visapost",
                              "occup",
                              "entdepa",
                              "entdepd",
                              "entdepu",
                              "matflag",
                              "biryear as birth_year",
                              "dtaddto as allowed_to_stay_until",
                              "gender",
                              "insnum as ins_num",
                              "airline",
                              "admnum as admission_num",
                              "fltno as flight_num",
                              "visatype as visa_type"])

i94_table.printSchema()

root
 |-- year: double (nullable = true)
 |-- month: double (nullable = true)
 |-- country_birth_id: double (nullable = true)
 |-- country_residence_id: double (nullable = true)
 |-- port_code: string (nullable = true)
 |-- arrival_date: double (nullable = true)
 |-- transport_mode: double (nullable = true)
 |-- state_code: string (nullable = true)
 |-- departure_from_usa: double (nullable = true)
 |-- age: double (nullable = true)
 |-- visa_code: double (nullable = true)
 |-- count: double (nullable = true)
 |-- dtadfile: string (nullable = true)
 |-- visapost: string (nullable = true)
 |-- occup: string (nullable = true)
 |-- entdepa: string (nullable = true)
 |-- entdepd: string (nullable = true)
 |-- entdepu: string (nullable = true)
 |-- matflag: string (nullable = true)
 |-- birth_year: double (nullable = true)
 |-- allowed_to_stay_until: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- ins_num: string (nullable = true)
 |-- airline: string (nullable = true)
 |-- admission_num: double (nullable = true)
 |-- flight_num: string (nullable = true)
 |-- visa_type: string (nullable = true)

In [13]:
i94_table.filter(i94_table.transport_mode==3.0).limit(10).toPandas()

,year,month,country_birth_id,country_residence_id,port_code,arrival_date,transport_mode,state_code,departure_from_usa,age,...,entdepu,matflag,birth_year,allowed_to_stay_until,gender,ins_num,airline,admission_num,flight_num,visa_type
0,2016.0,4.0,101.0,101.0,DAL,20559.0,3.0,NY,20562.0,27.0,...,None,M,1989.0,10142016,F,None,None,9.362681e+10,LAND,B2
1,2016.0,4.0,574.0,101.0,DET,20555.0,3.0,MO,NaN,38.0,...,None,None,1978.0,03142018,F,None,None,9.068215e+10,01601,E2
2,2016.0,4.0,101.0,101.0,DET,20567.0,3.0,None,20568.0,31.0,...,None,M,1985.0,05192016,F,None,None,7.986382e+10,LAND,B2
3,2016.0,4.0,101.0,101.0,DET,20574.0,3.0,MI,20576.0,27.0,...,None,M,1989.0,06242016,M,None,None,8.331251e+10,LAND,B2
4,2016.0,4.0,101.0,101.0,DET,20567.0,3.0,None,20569.0,60.0,...,None,M,1956.0,06292016,F,None,None,8.396096e+10,LAND,B2
5,2016.0,4.0,101.0,101.0,DET,20567.0,3.0,None,20569.0,65.0,...,None,M,1951.0,06292016,M,None,None,8.396123e+10,LAND,B2
6,2016.0,4.0,101.0,101.0,DET,20570.0,3.0,None,20643.0,32.0,...,None,M,1984.0,06292016,F,None,None,8.409472e+10,LAND,B2
7,2016.0,4.0,101.0,101.0,HOU,20552.0,3.0,NY,20555.0,34.0,...,None,M,1982.0,10072016,M,None,None,7.195148e+08,LAND,B2
8,2016.0,4.0,101.0,101.0,LEW,20574.0,3.0,None,20576.0,50.0,...,None,M,1966.0,08262016,F,None,None,8.917981e+10,LAND,B2
9,2016.0,4.0,101.0,101.0,LEW,20574.0,3.0,NY,20578.0,30.0,...,None,M,1986.0,10292016,M,None,None,9.500240e+10,LAND,B2

### Step 3: Define the Data Model
#### 3.1 Conceptual Data Model
Map out the conceptual data model and explain why you chose that model

#### 3.2 Mapping Out Data Pipelines
List the steps necessary to pipeline the data into the chosen data model

### Step 4: Run Pipelines to Model the Data 
#### 4.1 Create the data model
Build the data pipelines to create the data model.

In [ ]:
# Write code here

#### 4.2 Data Quality Checks
Explain the data quality checks you'll perform to ensure the pipeline ran as expected. These could include:
 * Integrity constraints on the relational database (e.g., unique key, data type, etc.)
 * Unit tests for the scripts to ensure they are doing the right thing
 * Source/Count checks to ensure completeness
 
Run Quality Checks

In [ ]:
# Perform quality checks here

#### 4.3 Data dictionary 
Create a data dictionary for your data model. For each field, provide a brief description of what the data is and where it came from. You can include the data dictionary in the notebook or in a separate file.

#### Step 5: Complete Project Write Up
* Clearly state the rationale for the choice of tools and technologies for the project.
* Propose how often the data should be updated and why.
* Write a description of how you would approach the problem differently under the following scenarios:
 * The data was increased by 100x.
 * The data populates a dashboard that must be updated on a daily basis by 7am every day.
 * The database needed to be accessed by 100+ people.

In [24]:
from extractor import Extractor

In [5]:
extractor = Extractor(spark, filepaths)

In [6]:
df_test = extractor.get_airport_data()
df_test.printSchema()

root
 |-- ident: string (nullable = true)
 |-- type: string (nullable = true)
 |-- name: string (nullable = true)
 |-- elevation_ft: string (nullable = true)
 |-- continent: string (nullable = true)
 |-- iso_country: string (nullable = true)
 |-- iso_region: string (nullable = true)
 |-- municipality: string (nullable = true)
 |-- gps_code: string (nullable = true)
 |-- iata_code: string (nullable = true)
 |-- local_code: string (nullable = true)
 |-- coordinates: string (nullable = true)